version: 38
jobs:
- name: Github Push
  steps:
  - !PushRepository
    name: gitcitadel
    remoteUrl: https://github.com/ShadowySupercode/gitcitadel
    passwordSecret: github_access_token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
