@startwbs Alexandria_v1.0_WBS

skinparam dpi 300
title Alexandria v 1.0 WBS

* Alexandria v 1.0
** v 0.1.0 Core features
*** Convert indextr client to new stylesheet
**** Tailwind theme
**** Svelte framework
**** Flowbite components
*** Connect to relays
*** Display global article feed
*** Login with browser extension
*** Upload articles
*** eBook format with 1 30040 to n 30041s
** v 0.2.0 Article management
*** Filter feeds by following/global
*** Remix articles
*** Comment on articles
*** Highlighter comments
** v 0.3.0 Extended features
*** Embedded links to other articles
*** Graph visualization
** v 0.4.0 Socializing
*** Communities and groups
*** Scheduling
*** Teleconference with chat

@endwbs
