@startwbs Alexandria_v1.0_WBS

<style>
wbsDiagram {
  .pink {
      BackgroundColor pink
  }
    .lightpink {
      BackgroundColor MistyRose
  }
}
</style>

skinparam dpi 300
title Alexandria v 1.0 WBS

* Alexandria v 1.0
** v 0.1.0 Core features
*** Convert indextr client to new stylesheet <<pink>>
**** Tailwind theme <<pink>>
**** Svelte framework <<pink>>
**** Flowbite components <<pink>>
*** Connect to relays <<pink>>
**** Display global article feed <<pink>>
**** Filter feeds by following/relay-global <<pink>>
*** Login <<pink>>
**** with browser extension <<pink>>
**** with bunker <<pink>>
*** Asciidoctor integration <<lightpink>>
**** Edit with preview <<pink>>
**** Compose <<lightpink>>
**** Publish events to relay
*** Reading view
**** Table of Contents <<pink>>
**** eBook format with 1 30040 to n 30041s <<pink>>
**** implement svelte-asciidoc rendering
*** Visualization page <<lightpink>>
**** reformat to new style <<pink>>
**** add node graph
*** About page <<lightpink>>
**** reformat to new style <<pink>>
** v 0.2.0 Article management
*** Handle more event types
**** Wiki pages
**** Articles (long-form)
**** Comments (kind 1111) on indexes
**** Highlights on Zettels
**** Kind 02 Hypernotes?
**** Embedded links to other articles and Nostr addresses
*** Relay management
*** Profile pages and bookmarking
** v 0.3.0 Advanced Article management
*** Create Alexandria Scribe AI assistant for VS Code <<lightpink>>
**** Add AI-assisted zettel generation and posting <<lightpink>>
**** Add content embeddings to posted zettels <<lightpink>>
*** Remix articles
*** Edit and forking of existing articles
** v 0.4.0 Reconstruction
*** Move from NDK to Aedile
*** ePaper app
*** Biblestr customization
**** Bible internal links
**** Preselection of favorite translations
**** Custom design
** v 0.5.0 Socializing
*** Communities and groups
*** Scheduled reads
*** Book clubs and Meet-the-author
*** Smart recommended reads
*** Teleconference with chat

@endwbs
