= BOOK II

1. Such then are the materials which we must employ in exhorting and dissuading, praising and blaming, accusing and defending, and such are the opinions and propositions that are useful to produce conviction in these circumstances; for they are the subject and source of enthymemes,
which are specially suitable to each class （so to say） of speeches.1 [2] But since the object of Rhetoric is judgement—for judgements are pronounced in deliberative rhetoric and judicial proceedings are a judgement—it is not only necessary to consider how to make the speech itself demonstrative and convincing, but also that the speaker should show himself to be of a certain character and should know how to put the judge into a certain frame of mind. [3] For it makes a great difference with regard to producing conviction—especially in demonstrative, and, next to this, in forensic oratory—that the speaker should show himself to be possessed of certain qualities and that his hearers should think that he is disposed in a certain way towards them; and further, that they themselves should be disposed in a certain way towards him.2 [4] In deliberative oratory, it is more useful that the orator should appear to be of a certain character, in forensic, that the hearer should be disposed in a certain way; for opinions vary, according as men love or hate, are wrathful or mild,
and things appear either altogether different, or different in degree; for when a man is favorably disposed towards one on whom he is passing judgement, he either thinks that the accused has committed no wrong at all or that his offence is trifling; but if he hates him, the reverse is the case. And if a man desires anything and has good hopes of getting it, if what is to come is pleasant, he thinks that it is sure to come to pass and will be good; but if a man is unemotional or not hopeful3 it is quite the reverse.

[5] For the orator to produce conviction three qualities are necessary; for, independently of demonstrations, the things which induce belief are three in number. These qualities are good sense, virtue, and goodwill; for speakers are wrong both in what they say and in the advice they give, because they lack either all three or one of them. [6] For either through want of sense they form incorrect opinions, or, if their opinions are correct, through viciousness they do not say what they think, or, if they are sensible and good,4 they lack goodwill; wherefore it may happen that they do not give the best advice, although they know what it is. These qualities are all that are necessary, so that the speaker who appears to possess all three will necessarily convince his hearers. [7] The means whereby he may appear sensible and good5 must be inferred from the classification of the virtues;6 for to make himself appear such he would employ the same means as he would in the case of others. We must now speak of goodwill and friendship in our discussion of the emotions.

[8] The emotions are all those affections which cause men to change their opinion in regard to their judgements, and are accompanied by pleasure and pain; such are anger, pity, fear, and all similar emotions and their contraries. [9] And each of them must be divided under three heads; for instance, in regard to anger, the disposition of mind which makes men angry, the persons with whom they are usually angry, and the occasions which give rise to anger. For if we knew one or even two of these heads, but not all three, it would be impossible to arouse that emotion. The same applies to the rest. Just as, then, we have given a list of propositions7 in what we have previously said, we will do the same here and divide the emotions in the same manner.

2. Let us then define anger as a longing, accompanied by pain, for a real or apparent revenge for a real or apparent slight,8 affecting a man himself or one of his friends, when such a slight is undeserved. [2] If this definition is correct, the angry man must always be angry with a particular individual （for instance, with Cleon, but not with men generally）,
and because this individual has done, or was on the point of doing, something against him or one of his friends; and lastly, anger is always accompanied by a certain pleasure, due to the hope of revenge to come. For it is pleasant to think that one will obtain what one aims at; now, no one aims at what is obviously impossible of attainment by him, and the angry man aims at what is possible for himself. Wherefore it has been well said of anger, that “ Far sweeter than dripping honey down the throat it spreads in men's hearts.9

” for it is accompanied by a certain pleasure, for this reason first,10 and also because men dwell upon the thought of revenge, and the vision that rises before us produces the same pleasure as one seen in dreams.

[3] Slighting is an actualization of opinion in regard to something which appears valueless; for things which are really bad or good, or tend to become so, we consider worthy of attention, but those which are of no importance or trifling11 we ignore. Now there are three kinds of slight: disdain, spitefulness, and insult. [4] For he who disdains, slights, since men disdain those things which they consider valueless and slight what is of no account. And the spiteful man appears to show disdain; for spitefulness consists in placing obstacles in the way of another's wishes, not in order that any advantage may accrue to him who spites, but to prevent any accruing to the other. Since then he does not act in this manner from self-interest, it is a slight;
for it is evident that he has no idea that the other is likely to hurt him, for in that case he would be afraid of him instead of slighting him; nor that he will be of any use to him worth speaking of, for in that case his thought would be how to become his friend.12

[5] Similarly, he who insults another also slights him; for insult13 consists in causing injury or annoyance whereby the sufferer is disgraced, not to obtain any other advantage for oneself besides the performance of the act, but for one's own pleasure; for retaliation is not insult, but punishment. [6] The cause of the pleasure felt by those who insult is the idea that, in ill-treating others, they are more fully showing superiority. That is why the young and the wealthy are given to insults; for they think that, in committing them, they are showing their superiority. Dishonor is characteristic of insult; and one who dishonors another slights him; for that which is worthless has no value, either as good or evil. Hence Achilles in his wrath exclaims: “ He has dishonored me, since he keeps the prize he has taken for himself,14

” and “ [has treated me] like a dishonored vagrant,15

” [7] as if being angry for these reasons. Now men think that they have a right to be highly esteemed by those who are inferior to them in birth, power, and virtue,
and generally, in whatever similar respect16 a man is far superior to another; for example, the rich man to the poor man in the matter of money, the eloquent to the incompetent speaker in the matter of oratory, the governor to the governed, and the man who thinks himself worthy to rule to one who is only fit to be ruled. Wherefore it has been said: “ Great is the wrath of kings cherished by Zeus,17

” and “ Yet it may be that even afterwards he cherishes his resentment,18

” for kings are resentful in consideration of their superior rank. [8] Further, men are angry at slights from those by whom they think they have a right to expect to be well treated; such are those on whom they have conferred or are conferring benefits, either themselves, or some one else for them, or one of their friends; and all those whom they desire, or did desire, to benefit.

[9] It is now evident from these considerations what is the disposition of those who are angry, with whom they are angry, and for what reasons. Men are angry when they are pained, because one who is pained aims at something; if then anyone directly opposes him in anything, as, for instance, prevents him from drinking when thirsty, or not directly, but seems to be doing just the same; and if anyone goes against him or refuses to assist him, or troubles him in any other way when he is in this frame of mind, he is angry with all such persons. [10] Wherefore the sick, the necessitous, [those at war], the lovesick, the thirsty, in a word, all who desire something and cannot obtain it, are prone to anger and easily excited, especially against those who make light of their present condition; for instance, the sick man is easily provoked in regard to his illness,19 the necessitous in regard to his poverty, the warrior in regard
to warlike affairs, the lover in regard to love affairs, and so with all the rest; for the passion20 present in his mind in each case paves the way for his anger. [11] Again, men are angry when the event is contrary to their expectation, for the more unexpected a thing is, the more it pains; just as they are overjoyed if, contrary to expectation, what they desire comes to pass. From this it is obvious what are the seasons, times, states of mind, and conditions of age in which we are easily moved21 to anger; and what are the various times, places, and reasons, which make us more prone to anger in proportion as we are subject to their influence.

[12] Such then are the dispositions of those who are easily roused to anger. As to the objects of their anger, men are angry with those who ridicule, mock, and scoff at them, for this is an insult. And with those who injure them in ways that are indications of insult. But these acts must be of such a kind that they are neither retaliatory nor advantageous to those who commit them; for if they are, they then appear due to gratuitous insult. [13] And men are angry with those who speak ill of or despise things which they themselves consider of the greatest importance; for instance, if a man speaks contemptuously of philosophy or of personal beauty in the presence of those who pride themselves upon them; and so in all other cases. [14] But they are far more angry if they suspect that they do not possess these qualities, either not at all, or not to any great extent, or when others do not think they possess them.
For when they feel strongly that they do possess those qualities which are the subject of mockery, they pay no heed to it. [15] And they are more angry with those who are their friends than with those who are not, for they think that they have a right to be treated well by them rather than ill. [16] And they are angry with those who have been in the habit of honoring and treating them with respect, if they no longer behave so towards them; for they think that they are being treated with contempt by them, otherwise they would treat them as before. [17] And with those who do not return their kindnesses nor requite them in full; and with those who oppose them, if they are inferiors; for all such appear to treat them with contempt, the latter as if they regarded them as inferiors, the former as if they had received kindnesses from inferiors.

[18] And they are more angry with those who are of no account, if they slight them; for anger at a slight was assumed to be felt at those who ought not to behave In such a manner; for inferiors ought not to slight their superiors. [19] And they are angry with friends, if they neither speak well of nor treat them well, and in an even greater degree, if they do the opposite. And if they fail to perceive that they want something from them, as Plexippus22 in Antiphon's tragedy reproached Meleager; for failure to perceive this is a sign of slight; since, when we care for people, these things are noticed.23 [20] And they are angry with those who rejoice, or in a general way are cheerful when they are unfortunate; for this is an indication of enmity or slight. And with those who do not care if they pain them;
whence they are angry with those who bring bad news. [21] And with those who listen to the tale of their faults, or look on them with indifference, for they resemble slighters or enemies; [22] for friends sympathize and all men are pained to see their own faults exposed.24 And further, with those who slight them before five classes of persons: namely, their rivals, those whom they admire, those by whom they would like to be admired, those whom they respect, or those who respect them; when anyone slights them before these, their anger is greater. [23] They are also angry with those who slight such persons as it would be disgraceful for them not to defend, for instance, parents, children, wives, and dependents.25 And with those who are ungrateful,26 for the slight is contrary to all sense of obligation. [24] And with those who employ irony, when they themselves are in earnest; [25] for irony shows contempt. And with those who do good to others, but not to them; for not to think them worthy of what they bestow upon all others also shows contempt. [26] Forgetfulness also is a cause of anger, such as forgetting names, although it is a mere trifle, since even forgetfulness seems a sign of slight; for it is caused by indifference, and indifference is a slight.
[27] We have thus stated at one and the same time the frame of mind and the reasons which make men angry, and the objects of their anger. It is evident then that it will be necessary for the speaker, by his eloquence, to put the hearers into the frame of mind of those who are inclined to anger, and to show that his opponents are responsible for things which rouse men to anger and are people of the kind with whom men are angry.

3. And since becoming angry is the opposite of becoming mild, and anger of mildness, we must determine the state of mind which makes men mild, towards whom they become mild, and the reasons which make them so. [2] Let us then define making mild as the quieting and appeasing of anger. [3] If then men are angry with those who slight them, and slight is voluntary, it is evident that they are mild towards those who do none of these things, or do them involuntarily, or at least appear to be such; [4] and towards those who intended the opposite of what they have done, and all who behave in the same way to themselves, for no one is likely to slight himself. [5] And towards those who admit and are sorry for a slight; for finding as it were satisfaction in the pain the offenders feel at what they have done, men cease to be angry. Evidence of this may be seen in the punishment of slaves; for we punish more severely those who contradict us and deny their offence, but cease to be angry with those who admit that they are justly punished. The reason is that to deny what is evident is disrespect, and disrespect
is slight and contempt; [6] anyhow, we show no respect for those for whom we entertain a profound contempt. Men also are mild towards those who humble themselves before them and do not contradict them, for they seem to recognize that they are inferior; now, those who are inferior are afraid, and no one who is afraid slights another. Even the behavior of dogs proves that anger ceases towards those who humble themselves, for they do not bite those who sit down.27 [7] And men are mild towards those who are serious with them when they are serious, for they think they are being treated seriously, not with contempt. [8] And towards those who have rendered them greater services.28 And towards those who want something and deprecate their anger, for they are humbler. [9] And towards those who refrain from insulting, mocking, or slighting anyone, or any virtuous man, or those who resemble themselves. [10] And generally speaking, one can determine the reasons that make for mildness by their opposites. Thus, men are mild towards those whom they fear or respect, as long as they feel so towards them, for it is impossible to be afraid and angry at the same time. [11] And against those who have acted in anger they either feel no anger or in a less degree, for they do not seem to have acted from a desire to slight. For no one slights another when angry, since slight is free from pain,
but anger is accompanied by it. [12] And men are not angry with those who usually show respect for them.29

It is also evident that those are mild whose condition is contrary to that which excites anger, as when laughing, in sport, at a feast, in prosperity, in success, in abundance,30 and, in general, in freedom from pain, in pleasure which does not imply insult, or in virtuous hope. Further, those whose anger is of long standing and not in its full flush, for time appeases anger. [13] Again, vengeance previously taken upon one person appeases anger against another, even though it be greater. Wherefore Philocrates,31 when someone asked him why he did not justify himself when the people were angry with him, made the judicious reply, “Not yet.” “When then?” “When I see someone accused of the same offence”; for men grow mild when they have exhausted their anger upon another, as happened in the case of Ergophilus.32 For although the Athenians were more indignant with him than with Callisthenes, they acquitted him, because they had condemned CalIicrates to death on the previous day. [14] Men also grow mild towards those whom they pity33; and if an offender has suffered greater evil than those who are angry would have inflicted, for they have an idea that they have as it were obtained reparation. [15] And if they think that they themselves are wrong and deserve what they suffer, for anger is not aroused against what is just; they no longer think that they are being treated otherwise than they should be, which, as we have said, is the essence of anger. Wherefore we should inflict a preliminary verbal chastisement, for even slaves are less indignant at punishment
of this kind. [16] And men are milder if they think that those punished will never know that the punishment comes from them in requital for their own wrongs; for anger has to do with the individual, as is clear from our definition.34 Wherefore it is justly said by the poet: “ Tell him that it is Odysseus, sacker of cities,35

” as if Polyphemus would not have been punished,36 had he remained ignorant who had blinded him and for what. So that men are not angry either with any others who cannot know who punishes them,37 or with the dead, since they have paid the last penalty and can feel neither pain nor anything else, which is the aim of those who are angry.38 So then, in regard to Hector, Homer, when desirous of restraining the anger of Achilles against a dead man, well says: “ For it is senseless clay that he outrages in his wrath.39

” [17] It is evident, then, that men must have recourse to these topics when they desire to appease their audience, putting them into the frame of mind required and representing those with whom they are angry as either formidable or deserving of respect, or as having rendered them great services, or acted involuntarily, or as exceedingly grieved at what they have done.

4. Let us now state who are the persons that men love40 or hate, and why, after we have defined love and loving. [2] Let loving, then, be defined as wishing for anyone the things which we believe to be good, for his sake but not for our own,
and procuring them for him as far as lies in our power. A friend is one who loves and is loved in return, and those who think their relationship is of this character consider themselves friends. [3] This being granted, it necessarily follows that he is a friend who shares our joy in good fortune and our sorrow in affliction, for our own sake and not for any other reason. For all men rejoice when what they desire comes to pass and are pained when the contrary happens, so that pain and pleasure are indications of their wish. [4] And those are friends who have the same ideas of good and bad, and love and hate the same persons, since they necessarily wish the same things; wherefore one who wishes for another what he wishes for himself seems to be the other's friend.

[5] We also like those who have done good either to us or to those whom we hold dear, if the services are important, or are cordially rendered, or under certain circumstances, and for our sake only; and all those whom we think desirous of doing us good. [6] And those who are friends of our friends and who like those whom we like, and those who are liked by those who are liked by us; [7] and those whose enemies are ours, those who hate those whom we ourselves hate, and those who are hated by those who are hated by us; for all such persons have the same idea as ourselves of what is good, so that they wish what is good for us, which, as we said, is the characteristic of a friend. [8] Further, we like those who are ready to help others in the matter of
money or personal safety; wherefore men honor those who are liberal and courageous and just. [9] And such we consider those who do not live upon others; the sort of men who live by their exertions, and among them agriculturists, and, beyond all others, those who work with their own hands.41 [10] And the self-controlled, because they are not likely to commit injustice; [11] and those who are not busybodies, for the same reason. And those with whom we wish to be friends, if they also seem to wish it; such are those who excel in virtue and enjoy a good reputation, either generally, or amongst the best, or amongst those who are admired by us or by whom we are admired.42 [12] Further, those who are agreeable to live or spend the time with; such are those who are good-tempered and not given to carping at our errors, neither quarrelsome nor contentious, for all such persons are pugnacious, and the wishes of the pugnacious appear to be opposed to ours.

[13] And those are liked who are clever at making or taking a joke, for each has the same end in view as his neighbor, being able to take a joke and return it in good taste. [14] And those who praise our good qualities, especially those which we ourselves are afraid we do not possess;
[15] those who are neat in their personal appearance and dress, and clean-living; [16] those who do not make our errors or the benefits they have conferred a matter of reproach, for both these are inclined to be censorious; [17] those who bear no malice and do not cherish the memory of their wrongs, but are easily appeased; for we think that they will be to ourselves such as we suppose them to be to others; [18] and those who are neither given to slander, or eager to know the faults of their neighbors nor our own, but only the good qualities; [19] for this is the way in which the good man acts. And those who do not oppose us when we are angry or occupied, for such persons are pugnacious; and those who show any good feeling towards us; for instance, if they admire us, think us good men, and take pleasure in our company, [20] especially those who are so disposed towards us in regard to things for which we particularly desire to be either admired or to be thought worthy or agreeable. [21] And we like those who resemble us and have the same tastes, provided their interests do not clash with ours and that they do not gain their living in the same way; for then it becomes a case of “ Potter [being jealous] of potter.43

” [22] And those who desire the same things, provided it is possible for us to share them; otherwise the same thing would happen again. [23] And those with whom we are on such terms that we do not blush before them for faults merely condemned by
public opinion, provided that this is not due to contempt; [24] and those before whom we do blush for faults that are really bad. And those whose rivals we are,44 or by whom we wish to be emulated, but not envied,—these we either like or wish to be friends with them. [25] And those whom we are ready to assist in obtaining what is good, provided greater evil does not result for ourselves. [26] And those who show equal fondness for friends, whether absent or present; wherefore all men like those who show such feeling for the dead.

In a word, men like those who are strongly attached to their friends and do not leave them in the lurch; for among good men they chiefly like those who are good friends. [27] And those who do not dissemble with them; such are those who do not fear to mention even their faults. （For, as we have said, before friends we do not blush for faults merely condemned by public opinion; if then he who blushes for such faults is not a friend, he who does not is likely to be one）.45 And men like those who are not formidable, and in whom they have confidence; for no one likes one whom he fears. [28] Companionship, intimacy, kinship, and similar relations are species of friendship. Things that create friendship are doing a favor, [29] and doing it unasked, and not making it public after doing it; for then it seems to have been rendered for the sake of the friend, and not for any other reason.

[30] As for enmity and hatred, it is evident that they must be examined in the light of their contraries. The causes which produce enmity are anger, spitefulness, slander. [31] Anger arises from acts committed against us, enmity even from those that are not; for if we imagine a man to be of such and such a character, we hate him. Anger has always an individual as its object, for instance Callias or Socrates, whereas hatred applies to classes; for instance, every one hates a thief or informer. Anger is curable by time, hatred not; the aim of anger is pain, of hatred evil; for the angry man wishes to see what happens;46 to one who hates it does not matter. Now, the things which cause pain are all perceptible, while things which are especially bad, such as injustice or folly, are least perceptible; for the presence of vice causes no pain. Anger is accompanied by pain, but hatred not; for he who is angry suffers pain, but he who hates does not. One who is angry might feel compassion in many cases, but one who hates, never; for the former wishes that the object of his anger should suffer in his turn, the latter, that he should perish. [32] It is evident, then, from what we have just said, that it is possible to prove that men are enemies or friends, or to make them such if they are not; to refute those who pretend that they are, and when they oppose us through anger or enmity, to bring them over to whichever side may be preferred.
The things and persons that men fear and in what frame of mind, will be evident from the following considerations.

5. Let fear be defined as a painful or troubled feeling caused by the impression of an imminent evil that causes destruction or pain; for men do not fear all evils, for instance, becoming unjust or slow-witted, but only such as involve great pain or destruction, and only if they appear to be not far off but near at hand and threatening, for men do not fear things that are very remote; all know that they have to die, but as death is not near at hand, they are indifferent. [2] If then this is fear, all things must be fearful that appear to have great power of destroying or inflicting injuries that tend to produce great pain. That is why even the signs of such misfortunes are fearful, for the fearful thing itself appears to be near at hand, and danger is the approach of anything fearful. [3] Such signs are the enmity and anger of those able to injure us in any way; for it is evident that they have the wish,47 so that they are not far from doing so. [4] And injustice possessed of power is fearful, for the unjust man is unjust through deliberate inclination.48
[5] And outraged virtue when it has power, for it is evident that it always desires satisfaction, whenever it is outraged, and now it has the power. [6] And fear felt by those able to injure us in any way, for such as these also must be ready to act. [7] And since most men are rather bad than good and the slaves of gain and cowardly in time of danger, being at the mercy of another is generally fearful, so that one who has committed a crime has reason to fear his accomplices as likely to denounce or leave him in the lurch. [8] And those who are able to ill-treat others are to be feared by those who can be so treated; for as a rule men do wrong whenever they can. Those who have been, or think they are being, wronged, are also to be feared, for they are ever on the look out for an opportunity. And those who have committed some wrong, when they have the power, since they are afraid of retaliation, [9] which was assumed to be something to be feared. And those who are our rivals for the same things, whenever it is impossible to share them, for men are always contending with such persons. [10] And those who are feared by those who are stronger than we are, for they would be better able to injure us, if they could injure those stronger than ourselves and those whom those who are stronger than ourselves are afraid of, for the same reason. [11] And those who have overthrown those who are stronger than us and those who attack those who are weaker, for they are either already to be feared, or will be, when they have grown stronger.

And among those whom we have wronged, or are our enemies or rivals,we should fear not the hot-tempered or
outspoken, but those who are mild, dissemblers, and thorough rascals; for it is uncertain whether they are on the point of acting, so that one never knows whether they are far from it.49 [12] All things that are to be feared are more so when, after an error has once been committed, it is impossible to repair it, either because it is absolutely impossible, or no longer in our power, but in that of our opponents; also when there is no possibility of help or it is not easy to obtain. In a word, all things are to be feared which, when they happen, or are on the point of happening, to others, excite compassion. These are, so to say, nearly all the most important things which are to be feared and which men fear. Let us now state the frame of mind which leads men to fear.

[13] If then fear is accompanied by the expectation that we are going to suffer some fatal misfortune, it is evident that none of those who think that they will suffer nothing at all is afraid either of those things which he does not think will happen to him, or of those from whom he does not expect them, or at a time when he does not think them likely to happen. It therefore needs be that those who think they are likely to suffer anything should be afraid, either of the persons at whose hands they expect it, or of certain things, and at certain times. [14] Those who either are, or seem to be, highly prosperous do not think they are likely to suffer anything;
wherefore they are insolent, contemptuous, and rash, and what makes them such is wealth, strength, a number of friends, power. It is the same with those who think that they have already suffered all possible ills and are coldly indifferent to the future, like those who are being beaten to death; for it is a necessary incentive to fear that there should remain some hope of being saved from the cause of their distress. A sign of this is that fear makes men deliberate, whereas no one deliberates about things that are hopeless. [15] So that whenever it is preferable that the audience should feel afraid, it is necessary to make them think they are likely to suffer, by reminding them that others greater than they have suffered, and showing that their equals are suffering or have suffered, and that at the hands of those from whom they did not expect it, in such a manner and at times when they did not think it likely.

[16] Now, since we have made clear what fear and fearful things are, and the frame of mind in each case which makes men fear, one can see from this what confidence is, what are the things that give it, and the frame of mind of those who possess it; for confidence is the contrary of fear and that which gives confidence of that which causes fear, so that the hope of what is salutary is accompanied by an impression that it is quite near at hand, while the things to be feared are either non-existent or far off. [17] Confidence is inspired by the remoteness of fearful things,
or by the nearness of things that justify it.50 If remedies are possible, if there are means of help, either great or numerous, or both; if we have neither committed nor suffered wrong if we have no rivals at all, or only such as are powerless, or, if they have power, are our friends, or have either done us good or have received it from us; if those whose interests are the same as ours are more numerous, or stronger, or both. [18] We feel confidence in the following states of mind: if we believe that we have often succeeded and have not suffered, or if we have often been in danger and escaped it; for men are unaffected by fear in two ways, either because they have never been tested or have means of help; thus, in dangers at sea, those who have never experienced a storm and those who have means of help as the result of experience have confidence as to the future. [19] We are also reassured, when a thing does not inspire fear in our equals, our inferiors, or those to whom we think ourselves superior; and we think ourselves superior to those whom we have conquered, either themselves or their superiors or equals. [20] And if we think we possess more or more considerable advantages, such as make their possessors formidable;
such are abundance of money, strength of body, friends, territory, military equipments, either all or the most important. And if we have never done wrong to anyone, or only to a few, or not to such as are to be feared; [21] and, generally, if it is well with us in regard to the gods, especially as to intimations from signs and oracles, and everything else of the kind; for anger inspires confidence, and it is the wrong that we suffer and not that which we inflict upon others that causes anger, and the gods are supposed to assist those who are wronged.51 [22] Lastly, we feel confidence when, at the beginning of any undertaking, we do not expect disaster either in the present or future, or hope for success. Such are the things that inspire fear or confidence.

6. What are the things of which men are ashamed or the contrary, and before whom, and in what frame of mind, will be clear from the following considerations. [2] Let shame then be defined as a kind of pain or uneasiness in respect of misdeeds, past, present, or future, which seem to tend to bring dishonor; and shamelessness as contempt and indifference in regard to these same things. [3] If this definition of shame is correct, it follows that we are ashamed of all such misdeeds as seem to be disgraceful, either for ourselves or for those whom we care for. Such are all those that are due to vice, such as throwing away one's shield or taking to flight, for this is due to cowardice;
or withholding a deposit, for this is due to injustice. [4] And illicit relations with any persons, at forbidden places or times, for this is due to licentiousness. [5] And making profit out of what is petty or disgraceful, or out of the weak, such as the indigent or dead; whence the proverb, “to rob even a corpse,” for this is due to base love of gain and stinginess. [6] And to refuse assistance in money matters when we are able to render it, or to give less than we can; to accept assistance from those less able to afford it than ourselves; [7] to borrow when anyone seems likely to ask for a loan, to ask for a loan from one who wants his money back, and asking for repayment from one who wants to borrow; to praise in order to seem to be asking for a loan, and when you have failed to obtain it to keep on asking; for all these are signs of stinginess. [8] And to praise people when they are present, to overpraise their good qualities and to palliate the bad, to show excessive grief at another's grief when present, and all similar actions; for they are signs of flattery.

[9] And not to submit to toils, which those put up with who are older
or live luxuriously or hold higher positions, or, generally speaking, are less fitted to do so; for all these are signs of effeminacy. [10] To accept favors from another and often, and then to throw them in his teeth; for all these things are signs of littleness and abasement of soul. [11] And to speak at great length about oneself and to make all kinds of professions, and to take the credit for what another has done; for this is a sign of boastfulness. Similarly, in regard to each of all the other vices of character, the acts resulting from them, their signs, and the things which resemble them, all these are disgraceful, and should make us ashamed. [12] It is also shameful not to have a share in the honorable things which all men, or all who resemble us, or the majority of them, have a share in. By those who resemble us I mean those of the same race, of the same city, of the same age, of the same family, and, generally speaking, those who are on an equality; for then it is disgraceful not to have a share, for instance, in education and other things, to the same extent. All these things are the more disgraceful, if the fault appears to be our own; for they are at once seen to be due rather to natural depravity if we ourselves are the cause of past, present, or future defects. [13] And we are ashamed when we suffer or have suffered or are likely to suffer things which tend to ignominy and reproach; such are prostituting one's person or performing disgraceful actions, including unnatural lust. And of these actions those that promote licentiousness are disgraceful, whether voluntary or involuntary （the latter being those that are done under compulsion）,
since meek endurance and the absence of resistance are the result of unmanliness or cowardice.

These and similar things are those of which men are ashamed. [14] And since shame is an impression about dishonor, and that for its own sake and not for its results; and since no one heeds the opinion of others except on account of those who hold it, it follows that men feel shame before those whom they esteem. [15] Now men esteem those who admire them and those whom they admire, those by whom they wish to be admired, those whose rivals they are, and whose opinion they do not despise. [16] They desire to be admired by those, and admire those who possess anything good that is greatly esteemed, or from whom they urgently require something which it is in their power to give, as is the case with lovers. [17] And they are rivals of those who are like them; and they give heed to the men of practical wisdom as likely to be truthful; such are the older and well educated. [18] They are also more ashamed of things that are done before their eyes and in broad daylight; whence the proverb, The eyes are the abode of shame.52 That is why they feel more ashamed before those who are likely to be always with them or who keep watch upon them,
because in both cases they are under the eyes of others.

[19] Men are also ashamed before those who are not open to the same accusations, for it is evident that their feelings are contrary. And before those who are not indulgent towards those who appear to err; for a man is supposed not to reproach others with what he does himself, so it is clear that what he reproaches them with is what he does not do himself. [20] And before those who are fond of gossiping generally; for not to gossip about the fault of another amounts to not regarding it as a fault at all. Now those who are inclined to gossip are those who have suffered wrong, because they always have their eyes upon us; and slanderers, because, if they traduce the innocent, still more will they traduce the guilty. And before those who spend their time in looking for their neighbors' faults, for instance, mockers and comic poets; for they are also in a manner slanderers and gossips. And before those from whom they have never asked anything in vain,53 for they feel as if they were greatly esteemed. For this reason they feel ashamed before those who ask them for something for the first time, as never yet having lost their good opinion. Such are those who have recently sought their friendship （for they have only seen what is best in them, which is the point of the answer of Euripides to the Syracusans）,54 or old acquaintances who know nothing against us. [21] And men are ashamed not only of the disgraceful things we have spoken of, but also of indications of them, for instance, not only of sensual pleasures, but also of the indications of them; and not only of doing, [22] but also
of saying disgraceful things. Similarly, men are ashamed not only before those who have been mentioned, but also before those who will reveal their faults to them, such as their servants or friends. [23] In a word, they are not ashamed either before those whose opinion in regard to the truth they greatly despise—for instance, no one feels shame before children or animals—or of the same things before those who are known to them and those who are not; before the former, they are ashamed of things that appear really disgraceful, before strangers, of those which are only condemned by convention.

[24] Men are likely to feel shame in the following situations; first, if there are any who are so related to them as those before whom we said that they feel shame. These, as we pointed out, are those who are admired by them or who admire them, or by whom they wish to be admired, or from whom they need some service, which they will not obtain if they lose their reputation. These, again, are either persons who directly see what is going on （just as Cydias, when haranguing the people about the allotment of the territory of Samos, begged the Athenians to picture to themselves that the Greeks were standing round them and would not only hear, but also see what they were going to decree）; or neighbors; or those likely to be aware of what they say or do. That is why men do not like, when unfortunate, to be seen by those who were once their rivals,
for rivalry presumes admiration. [25] Men also feel shame when they are connected with actions or things which entail disgrace,55 for which either they themselves, or their ancestors, or any others with whom they are closely connected are responsible. In a word, men feel shame for those whom they themselves respect;56 such are those mentioned and those who have any relation to them, for instance, whose teachers or advisers they have been; similarly, when they are in rivalry with others who are like them; [26] for there are many things which they either do or do not do owing to the feeling of shame which these men inspire. [27] And they are more likely to be ashamed when they have to be seen and to associate openly with those who are aware of their disgrace. Wherefore the tragic poet Antiphon,57 when he was about to be flogged to death by order of Dionysius, seeing that those who were to die with him covered their faces as they passed through the gates, said, “Why cover your faces? Is it because you are afraid that one of the crowd should see you tomorrow?” Let this account of shame suffice; as for shamelessness, it is evident that we shall be able to obtain ample knowledge of it from the contrary arguments.

7. The persons towards whom men feel benevolent,58 and for what reasons, and in what frame of mind, will be clear when we have defined what favor is. [2] Let it then be taken to be the feeling in accordance with which one who has it is said to render a service to one who needs it, not in return for something nor in the interest of him who renders it, but in that of the recipient. And the favor will be great
if the recipient is in pressing need, or if the service or the times and circumstances are important or difficult, or if the benefactor is the only one, or the first who has rendered it, or has done so in the highest degree. [3] By needs I mean longings, especially for things the failure to obtain which is accompanied by pain; such are the desires, for instance, love; also those which arise in bodily sufferings and dangers, for when a man is in pain or danger he desires something. That is why those who help a man who is poor or an exile, even if the service be ever so small, are regarded with favor owing to the urgency and occasion of the need; for instance, the man who gave the mat59 to another in the Lyceum. [4] It is necessary then, if possible, that the service should be in the same direction60; if not, that it should apply to cases of similar or greater need.

Since then it is evident on what occasions,61 for what reasons, and in what frame of mind a feeling of benevolence arises, it is clear that we must derive our arguments from this—to show that the one side either has been, or still is, in such pain or need, and that the other has rendered, or is rendering, such a service in such a time of need. [5] It is evident also by what means it is possible to make out that there is no favor at all, or that those who render it are not actuated by benevolence62;
for it can either be said that they do, or have done so, for their own sake, in which case there is no favor; or that it was mere chance; or that they acted under compulsion; or that they were making a return, not a gift, whether they knew it or not; for in both cases it is an equivalent return, so that in this case also there is no favor. [6] And the action must be considered in reference to all the categories; for if there is a favor it is so because of substance, quantity, quality, time, or place.63 And it denotes lack of goodwill, if persons have not rendered a smaller service,64 or if they have rendered similar, equal, or greater services to our enemies; for it is evident that they do not act for our sake in this case either. Or if the service was insignificant, and rendered by one who knew it; for no one admits that he has need of what is insignificant.

8. Let this suffice for benevolence and the opposite. We will now state what things and persons excite pity, and the state of mind of those who feel it. [2] Let pity then be a kind of pain excited by the sight of evil, deadly or painful, which befalls one who does not deserve it; an evil which one might expect to come upon himself or one of his friends, and when it seems near. For it is evident that one who is likely to feel pity must be such as to think that he, or one of his friends, is liable to suffer some evil, and such an evil as has been stated in the definition, or one similar, or nearly similar. [3] Wherefore neither those who are utterly ruined,
are capable of pity, for they think they have nothing more to suffer, since they have exhausted suffering; nor those who think themselves supremely fortunate, who rather are insolent. For if they think that all good things are theirs, it is clear that they think that they cannot possibly suffer evil, and this is one of the good things. [4] Now those persons who think they are likely to suffer are those who have already suffered and escaped; the advanced in age, by reason of their wisdom and experience; and the weak, and those who are rather more timid; and the educated, for they reckon rightly; [5] and those who have parents, children, or wives, for these are part of them and likely to suffer the evils of which we have spoken; [6] and those who are not influenced by any courageous emotion, such as anger or confidence, for these emotions do not take thought of the future and those who are not in a wantonly insolent frame of mind, for they also take no thought of future suffering; but it is those who are between the two extremes that feel pity. Those who are not in great fear; for those who are panic-stricken are incapable of pity, because they are preoccupied with their own emotion. [7] And men feel pity if they think that some persons are virtuous; for he who thinks that no one is will think that all deserve misfortune.
And, generally speaking, a man is moved to pity when he is so affected that he remembers that such evils have happened, or expects that they may happen, either to himself or to one of his friends.

[8] We have stated the frame of mind which leads men to pity; and the things which arouse this feeling are clearly shown by the definition. They are all painful and distressing things that are also destructive, and all that are ruinous; and all evils of which fortune is the cause, if they are great. [9] Things distressing and destructive are various kinds of death, personal ill-treatment and injuries, old age, disease, and lack of food. [10] The evils for which fortune is responsible are lack of friends, or few friends （wherefore it is pitiable to be torn away from friends and intimates）, ugliness, weakness, mutilation; if some misfortune comes to pass from a quarter whence one might have reasonably expected something good; [11] and if this happens often; and if good fortune does not come until a man has already suffered, as when the presents from the Great King were not dispatched to Diopithes until he was dead. Those also are to be pitied to whom no good has ever accrued, or who are unable to enjoy it when it has.

These and the like things, then, excite pity. [12] The persons men pity are those whom they know, provided they are not too closely connected with them for if they are, they feel the same as if they themselves were likely
to suffer. This is why Amasis65 is said not to have wept when his son was led to execution, but did weep at the sight of a friend reduced to beggary, for the latter excited pity, the former terror. The terrible is different from the pitiable, for it drives out pity, and often serves to produce the opposite feeling. [13] Further, the nearness of the terrible makes men pity.66 Men also pity those who resemble them in age, character, habits, position, or family; for all such relations make a man more likely to think that their misfortune may befall him as well. For, in general, here also we may conclude that all that men fear in regard to themselves excites their pity when others are the victims. [14] And since sufferings are pitiable when they appear close at hand, while those that are past or future, ten thousand years backwards or forwards, either do not excite pity at all or only in a less degree, because men neither expect the one nor remember the other, it follows that those who contribute to the effect by gestures, voice, dress, and dramatic action generally, are more pitiable; for they make the evil appear close at hand, setting it before our eyes as either future or past.
[15] And disasters that have just happened or are soon about to happen excite more pity for the same reason. [16] Pity is also aroused by signs and actions, such as the dress of those who have suffered, and all such objects, and the words and everything else that concerns those who are actually suffering, for instance, at the point of death. And when men show themselves undaunted67 at such critical times it is specially pitiable; for all these things,68 because they come immediately under our observation, increase the feeling of pity, both because the sufferer does not seem to deserve his fate, and because the suffering is before our eyes.

9. Now what is called indignation69 is the antithesis to pity; for the being pained at undeserved good fortune is in a manner contrary to being pained at undeserved bad fortune and arises from the same character. And both emotions show good character, [2] for if we sympathize with and pity those who suffer undeservedly, we ought to be indignant with those who prosper undeservedly; for that which happens beyond a man's deserts is unjust, wherefore we attribute this feeling even to gods. [3] It would seem that envy also is similarly opposed to pity, as being akin to or identical with indignation, although it is really different; envy also is indeed a disturbing pain and directed against good fortune, but not that of one who does not deserve it, but of one who is our equal and
like. Now, all who feel envy and indignation must have this in common, that they are disturbed, not because they think that any harm will happen to themselves, but on account of their neighbor; for it will cease to be indignation and envy, but will be fear, if the pain and disturbance arise from the idea that harm may come to themselves from another's good fortune. [4] And it is evident that these feelings will be accompanied by opposite feelings; for he who is pained at the sight of those who are undeservedly unfortunate will rejoice or will at least not be pained at the sight of those who are deservedly so; for instance, no good man would be pained at seeing parricides or assassins punished; we should rather rejoice at their lot, and at that of men who are deservedly fortunate; for both these70 are just and cause the worthy man to rejoice, because he cannot help hoping that what has happened to his like may also happen to himself. [5] And all these feelings arise from the same character and their contraries from the contrary; for he who is malicious is also envious,
since, if the envious man is pained at another's possession or acquisition of good fortune, he is bound to rejoice at the destruction or non-acquisition of the same. Wherefore all these emotions are a hindrance to pity, although they differ for the reasons stated; so that they are all equally useful for preventing any feeling of pity.

[6] Let us then first speak of indignation, the persons with whom men feel indignant, for what reasons, and in what frame of mind; and then proceed to the rest of the emotions. [7] What we have just said will make matters clear. For if indignation is being pained at the sight of good fortune that is apparently undeserved, in the first place it is clear that it is not possible to feel indignation at all good things; [8] for no one will be indignant with a man who is just or courageous, or may acquire any virtue （for one does not feel pity in the case of opposites of those qualities）,71 but men are indignant at wealth, power, in a word, at all the advantages of which good men are worthy. [And those who possess natural advantages, such as noble birth, beauty, and all such things.]72 [9] And since that which is old seems closely to resemble that which is natural, it follows that, if two parties have the same good, men are more indignant with the one who has recently acquired it and owes his prosperity to it; for the newly rich cause more annoyance than those who have long possessed or inherited wealth. The same applies to offices of state,
power, numerous friends, virtuous children, and any other advantages of the kind. And if these advantages bring them some other advantage, men are equally indignant; for in this case also the newly rich who attain to office owing to their wealth cause more annoyance than those who have long been wealthy; and similarly in all other cases of the same kind. [10] The reason is that the latter seem to possess what belongs to them, the former not; for that which all along shows itself in the same light suggests a reality, so that the former seem to possess what is not theirs.73 [11] And since every kind of good is not suitable to the first comer, but a certain proportion and suitability are necessary （as for instance beautiful weapons are not suitable to the just but to the courageous man, and distinguished marriages not to the newly rich but to the nobly born）, if a virtuous man does not obtain what is suitable to him, we feel indignant. Similarly, if the inferior contends with the superior, especially among those engaged in the same pursuit,—whence the saying of the poet, “ He avoided battle with Ajax, son of Telamon,74 for Zeus was indignant with him, when he would fight with a better man;

”
or, if the pursuit is not the same, wherever the inferior contends with the superior in anything whatever, as for instance, the musician with the just man; for justice is better than music.

From this it is clear, then, with whom men are indignant and for what reasons; they are these or of such a kind. [12] Men are prone to indignation, first, if they happen to deserve or possess the greatest advantages, for it is not just that those who do not resemble them should be deemed worthy of the same advantages; [13] secondly, if they happen to be virtuous and worthy,75 for they both judge correctly and hate what is unjust. [14] And those who are ambitious and long for certain positions, especially if they are those which others, although unworthy, have obtained.76 [15] And, in general, those who think themselves worthy of advantages of which they consider others unworthy, are inclined to be indignant with the latter and because of these advantages. This is why the servile and worthless and unambitious are not inclined to indignation; for there is nothing of which they think themselves worthy. [16] It is evident from this what kind of men they are whose ill fortunes, calamities, and lack of success must make us rejoice or at least feel no pain; for the opposites are clear from what has been said. If then the speaker puts the judges into such a frame of mind and proves that
those who claim our pity （and the reasons why they do so） are unworthy to obtain it and deserve that it should be refused them, then pity will be impossible.

10. It is equally clear for what reason, and of whom, and in what frame of mind, men are envious, if envy is a kind of pain at the sight of good fortune in regard to the goods mentioned; in the case of those like themselves; and not for the sake of a man getting anything, but because of others possessing it. For those men will be envious who have, or seem to have, others “like” them. [2] I mean like in birth, relationship, age, moral habit, reputation, and possessions. And those will be envious who possess all but one of these advantages77; that is why those who attempt great things and succeed are envious, because they think that every one is trying to deprive them of their own. [3] And those who are honored for some special reason, especially for wisdom or happiness. And the ambitious are more envious than the unambitious. And those who are wise in their own conceit, for they are ambitious of a reputation for wisdom; and, in general, those who wish to be distinguished in anything are envious in regard to it. And the little-minded, because everything appears to them to be great.

[4] The advantages which excite envy have already been stated.
Nearly all the actions or possessions which make men desire glory or honor and long for fame, and the favors of fortune, create envy, especially when men long for them themselves, or think that they have a right to them, or the possession of which makes them slightly superior or slightly inferior.

[5] And it is evident whom men envy, for it has just been stated by implication. They envy those who are near them in time, place, age, and reputation, whence it was said, “ Kinship knows how to envy also;78

” and those with whom they are in rivalry, who are those just spoken of; for no man tries to rival those who lived ten thousand years ago, or are about to be born, or are already dead; nor those who live near the Pillars of Hercules;79 nor those who, in his own opinion or in that of others, are either far inferior or superior to him; and the people and things which one envies are on the same footing.80 [6] And since men strive for honor with those who are competitors, or rivals in love, in short, with those who aim at the same things, they are bound to feel most envious of these; whence the saying, “ Potter [being jealous] of potter.81

” [7] And those who have succeeded with difficulty or have failed envy those whose success has been rapid. [8] And those whose possessions or successes are a reproach to themselves, and these, too, are those near or like them; for it is clear that it is their own fault
that they do not obtain the same advantage, so that this pains and causes envy. [9] And those who either have or have acquired what was naturally theirs or what they had once acquired; this is why an older man is envious of a younger one. [10] Those who have spent much envy those who have only spent little to obtain the same thing. [11] And it is clear at what things and persons the envious rejoice, and in what frame of mind; for, as when they do not possess certain things, they are pained, so when they do possess them, they will rejoice in the opposite circumstances.82 So that if the judges are brought into that frame of mind, and those who claim their pity or any other boon are such as we have stated, it is plain that they will not obtain pity from those with whom the decision rests.

11. The frame of mind in which men feel emulation, what things and persons give rise to it, will be clear from the following considerations. Let us assume that emulation is a feeling of pain at the evident presence of highly valued goods, which are possible for us to obtain, in the possession of those who naturally resemble us—pain not due to the fact that another possesses them, but to the fact that we ourselves do not. Emulation therefore is virtuous and characteristic of virtuous men, whereas envy is base and characteristic of base men; for the one, owing to emulation, fits himself to obtain such goods, while the object of the other, owing to envy, is to prevent his neighbor possessing them.
Necessarily, then, those are emulous who hold that they have a claim to goods that they do not possess;83 for no one claims what seems impossible. [2] Hence the young and high-minded are emulous. And so are those who possess such advantages as are worthy of honorable men, which include wealth, a number of friends, positions of office, and all similar things. For, believing it their duty to be good, because such goods naturally belong to those who are good, they strive to preserve them. And those are emulous, whom others think worthy of them. [3] Honors obtained by ancestors, kinsfolk, intimates, nation, or city make men emulous in regard to such honors; for they think that these honors really belong to them and that they are worthy of them. [4] And if highly valued goods are the object of emulation, it necessarily follows that the virtues must be such and all things that are useful and beneficial to the rest of mankind, for benefactors and virtuous men are honored; to these we may add all the goods which our neighbors can enjoy with us, such as wealth and beauty, rather than health.84

[5] It is also evident who are the objects of emulation; for they are those who possess these or similar goods, such as have already been spoken of, for instance, courage, wisdom, authority; for those in authority, such as generals, orators, and all who have similar powers, can do good to many. [6] And those whom many desire to be like, or to be their acquaintances
or friends;85 those whom many or ourselves admire; [7] those who are praised or eulogized either by poets or by prose writers.86 The opposite characters we despise; for contempt is the opposite of emulation, and the idea of emulation of the idea of contempt. And those who are in a condition which makes them emulate, or be emulated by, others, must be inclined to despise those persons87 （and for that reason） who suffer from defects contrary to the good things which excite emulation. That is why we often despise those who are fortunate, whenever their good fortune is not accompanied by highly valued goods. The means of producing and destroying the various emotions in men, from which the methods of persuasion that concern them are derived, have now been stated.

12. Let us now describe the nature of the characters of men according to their emotions, habits, ages, and fortunes. [2] By the emotions I mean anger, desire, and the like, of which we have already spoken; by habits virtues and vices, of which also we have previously spoken, as well as the kind of things men individually and deliberately choose and practise. The ages are youth, the prime of life, and old age.
By fortune I mean noble birth, wealth, power, and their contraries, and, in general, good or bad fortune.88

[3] The young, as to character, are ready to desire and to carry out what they desire. Of the bodily desires they chiefly obey those of sensual pleasure and these they are unable to control. [4] Changeable in their desires and soon tiring of them, they desire with extreme ardor, but soon cool; for their will, like the hunger and thirst of the sick, is keen rather than strong. [5] They are passionate, hot-tempered, and carried away by impulse, and unable to control their passion; for owing to their ambition they cannot endure to be slighted, and become indignant when they think they are being wronged. [6] They are ambitious of honor, but more so of victory; for youth desires superiority, and victory is a kind of superiority. And their desire for both these is greater than their desire for money, to which they attach only the slightest value, because they have never yet experienced want, as Pittacus89 said in his pithy remark on Amphiaraus. [7] They are not ill-natured but simple-natured,90 because they have never yet witnessed much depravity; confiding, because they have as yet not been often deceived; [8] full of hope, for they are naturally as hot-blooded as those who are drunken with wine, and besides they have
not yet experienced many failures. For the most part they live in hope, for hope is concerned with the future as memory is with the past. For the young the future is long, the past short; for in the morning of life it is not possible for them to remember anything, but they have everything to hope; which makes them easy to deceive, for they readily hope. [9] And they are more courageous, for they are full of passion and hope, and the former of these prevents them fearing, while the latter inspires them with confidence, for no one fears when angry, and hope of some advantage inspires confidence. [10] And they are bashful, for as yet they fail to conceive of other things that are noble, but have been educated solely by convention.91 [11] They are high-minded, for they have not yet been humbled by life nor have they experienced the force of necessity; further, there is high-mindedness in thinking oneself worthy of great things, a feeling which belongs to one who is full of hope.

[12] In their actions, they prefer the noble to the useful; their life is guided by their character92 rather than by calculation, for the latter aims at the useful, virtue at the noble. [13] At this age more than any other they are fond of their friends and companions
because they take pleasure in living in company and as yet judge nothing by expediency, not even their friends. [14] All their errors are due to excess and vehemence and their neglect of the maxim of Chilon,93 for they do everything to excess, love, hate, and everything else. And they think they know everything, and confidently affirm it, and this is the cause of their excess in everything. [15] If they do wrong, it is due to insolence, not to wickedness. And they are inclined to pity, because they think all men are virtuous and better than themselves94; for they measure their neighbors by their own inoffensiveness, so that they think that they suffer undeservedly. [16] And they are fond of laughter, and therefore witty; for wit is cultured insolence. Such then is the character of the young.

13. Older men and those who have passed their prime have in most cases characters opposite to those of the young. For, owing to their having lived many years and having been more often deceived by others or made more mistakes themselves, and since most human things turn out badly, they are positive about nothing, and in everything they show an excessive lack of energy. [2] They always “think,” but “know” nothing; and in their hesitation they always add “perhaps,” or “maybe”; all their
statements are of this kind, never unqualified. [3] They are malicious; for malice consists in looking upon the worse side of everything. Further, they are always suspicious owing to mistrust, and mistrustful owing to experience. [4] And neither their love nor their hatred is strong for the same reasons; but, according to the precept of Bias,95 they love as if they would one day hate, and hate as if they would one day love. [5] And they are little-minded, because they have been humbled by life; for they desire nothing great or uncommon, but only the necessaries of life. [6] They are not generous, for property is one of these necessaries, and at the same time, they know from experience how hard it is to get and how easy to lose. [7] And they are cowardly and inclined to anticipate evil, for their state of mind is the opposite of that of the young; they are chilled, whereas the young are hot, so that old age paves the way for cowardice, for fear is a kind of chill. [8] And they are fond of life, especially in their last days, because desire is directed towards that which is absent and men especially desire what they lack. [9] And they are unduly selfish, for this also is littleness of mind. And they live not for the noble, but for the useful, more than they ought, because they are selfish;
for the useful is a good for the individual, whereas the noble is good absolutely.

[10] And they are rather shameless than modest; for since they do not care for the noble so much as for the useful, they pay little attention to what people think. [11] And they are little given to hope owing to their experience, for things that happen are mostly bad and at all events generally turn out for the worse, and also owing to their cowardice. [12] They live in memory rather than in hope; for the life that remains to them is short, but that which is past is long, and hope belongs to the future, memory to the past. This is the reason of their loquacity; for they are incessantly talking of the past, because they take pleasure in recollection. [13] Their outbursts of anger are violent, but feeble; of their desires some have ceased, while others are weak, so that they neither feel them nor act in accordance with them, but only from motives of gain. Hence men of this age are regarded as self-controlled, for their desires have slackened, and they are slaves to gain. [14] In their manner of life there is more calculation than moral character, for calculation is concerned with that which is useful, moral character with virtue. If they commit acts of injustice it is due to vice rather than to insolence. [15] The old, like the young, are inclined to pity, but not for the same reason; the latter show pity
from humanity, the former from weakness, because they think that they are on the point of suffering all kinds of misfortunes, and this is one of the reasons that incline men to pity. That is why the old are querulous, and neither witty nor fond of laughter; for a querulous disposition is the opposite of a love of laughter. [16] Such are the characters of the young and older men. Wherefore, since all men are willing to listen to speeches which harmonize with their own character and to speakers who resemble them,96 it is easy to see what language we must employ so that both ourselves and our speeches may appear to be of such and such a character.

14. It is evident that the character of those in the prime of life will be the mean between that of the other two, if the excess in each case be removed. At this age, men are neither over-confident, which would show rashness, nor too fearful, but preserving a right attitude in regard to both, [2] neither trusting nor distrusting all, but judging rather in accordance with actual facts. Their rule of conduct is neither the noble nor the useful alone,
but both at once. They are neither parsimonious nor prodigal, but preserve the due mean. [3] It is the same in regard to passion and desire. Their self-control is combined with courage and their courage with self-control, whereas in the young and old these qualities are found separately; for the young are courageous but without self-control, the old are self-controlled but cowardly. Speaking generally, all the advantages that youth and old age possess separately, those in the prime of life possess combined; and all cases of excess or defect in the other two are replaced by due moderation and fitness. [4] The body is most fully developed from thirty to thirty-five years of age, the mind at about forty-nine. Let this suffice for youth, old age, and the prime of life, and the characters which belong to each.

15. Let us next speak of the goods that are due to fortune, all those, at least, which produce certain characters in men. [2] A characteristic of noble birth is that he who possesses it is more ambitious; for all men, when they start with any good, are accustomed to heap it up, and noble birth is a heritage of honor from one's ancestors. Such men are prone to look down even upon those who are as important as their ancestors,
because the same things97 are more honorable and inspire greater vanity when remote than when they are recent. [3] The idea of noble birth refers to excellence of race, that of noble character to not degenerating from the family type, a quality not as a rule found in those of noble birth, most of whom are good for nothing. For in the generations of men there is a kind of crop as in the fruits of the field; sometimes, if the race is good, for a certain period men out of the common are born in it, and then it deteriorates. Highly gifted families often degenerate into maniacs, as, for example, the descendants of Alcibiades and the elder Dionysius; those that are stable into fools and dullards, like the descendants of Cimon, Pericles, and Socrates.

16. The characters which accompany wealth are plain for all to see. The wealthy are insolent and arrogant, being mentally affected by the acquisition of wealth, for they seem to think that they possess all good things;
for wealth is a kind of standard of value of everything else, so that everything seems purchasable by it. [2] They are luxurious and swaggerers, luxurious because of their luxury and the display of their prosperity, swaggerers and ill-mannered because all men are accustomed to devote their attention to what they like and admire, and the rich suppose that what they themselves are emulous of is the object of all other men's emulation. At the same time this feeling is not unreasonable; for those who have need of the wealthy are many in number. Hence the answer of Simonides to the wife of Hiero concerning the wise and the rich, when she asked which was preferable, to be wise or to be rich. “Rich,” he answered, “for we see the wise spending their time at the doors of the rich.” [3] And the rich think they are worthy to rule, because they believe they possess that which makes them so.98 In a word, the character of the rich man is that of a fool favored by fortune. [4] At the same time there is a difference between the character of the newly rich and of those whose wealth is of long standing, because the former have the vices of wealth in a greater degree and more; for, so to say, they have not been educated to the use of wealth. Their unjust acts are not due to malice, but partly to insolence, partly to incontinence, which tends to make them commit assault and battery and adultery.

17. In regard to power, nearly all the characters to which it gives rise are equally clear; for power, compared with wealth, exhibits partly identical, and partly superior characteristics. [2] Thus, the powerful are more ambitious and more manly in character than the rich, since they aim at the performance of deeds which their power gives them the opportunity of carrying out. [3] And they are more energetic; for being obliged to look after their power, they are always on the watch.99 [4] And they are dignified rather than heavily pompous; for their rank renders them more conspicuous, so that they avoid excess; and this dignity is a mild and decent pomposity. And their wrongdoings are never petty, but great.

[5] Good fortune in its divisions100 exhibits characters corresponding to those which have just been mentioned; for those which appear to be the most important kinds of good fortune tend in their direction; further, good fortune furnishes advantages over others in the blessing of children and bodily goods.
[6] Now, although men are more arrogant and thoughtless owing to good fortune, it is accompanied by a most precious quality. Fortunate men stand in a certain relation to the divinity and love the gods, having confidence in them owing to the benefits they have received from fortune. We have spoken101 of the characters associated with different ages and fortunes; the opposite characters to those described, for instance, of the poor, of the unfortunate, and of the weak, are obvious from their opposites.

18. Now102 the employment of persuasive speeches is directed towards a judgement; for when a thing is known and judged, there is no longer any need of argument. And there is judgement, whether a speaker addresses himself to a single individual and makes use of his speech to exhort or dissuade, as those do who give advice or try to persuade, for this single individual is equally a judge, since, speaking generally, he who has to be persuaded is a judge; if the speaker is arguing against an opponent or against some theory, it is just the same, for it is necessary to make use of speech to destroy the opposing arguments, against which he speaks as if they were the actual opponent; and similarly in epideictic speeches, for the speech is put together with reference to the spectator as if he were a judge. Generally speaking, however, only he who decides questions at issue in civil controversies103 is a judge in the proper sense of the word, for in judicial cases the point at issue is the state of the case, in deliberative the subjects of deliberation.104 We have already spoken of the characters of forms of government in treating
of deliberative rhetoric,105 so that it has been determined how and by what means we must make our speeches conform to those characters.

[2] Now, since each kind of Rhetoric, as was said,106 has its own special end, and in regard to all of them we have gathered popular opinions and premises whence men derive their proofs in deliberative, epideictic, and judicial speeches,107 and, further, we have determined108 the special rules according to which it is possible to make our speeches ethical, it only remains to discuss the topics common to the three kinds of rhetoric. [3] For all orators are obliged, in their speeches, also to make use of the topic of the possible and impossible, and to endeavor to show, some of them that a thing will happen, others that it has happened. [4] Further, the topic of magnitude is common to all kinds of Rhetoric, for all men employ extenuation or amplification whether deliberating, praising or blaming, accusing or defending.
[5] When these topics have been determined, we will endeavor to say what we can in general about enthymemes and examples, in order that, when we have added what remains, we may carry out what we proposed at the outset. Now, of the commonplaces amplification is most appropriate to epideictic rhetoric, as has been stated;109 the past to forensic, since things past are the subject of judgement; and the possible and future to deliberative.

19. Let us first speak of the possible and the impossible. If of two contrary things it is possible that one should exist or come into existence, then it would seem that the other is equally possible; for instance, if a man can be cured, he can also be ill; for the potentiality of contraries, qua contraries, is the same.110 Similarly, if of two like things the one is possible, so also is the other. [2] And if the harder of two things is possible, so also is the easier. [3] And if it is possible for a thing to be made excellent or beautiful, [4] it is possible for it to be made in general; for it is harder for a beautiful house to be made than a mere house.111 [5] Again, if the beginning is possible, so also is the end; for no impossible thing comes, or begins to come, into existence; for instance, that the diameter of a square should be commensurable with the side of a square is neither possible nor could be possible. And when the end is possible, so also is the beginning; for all things arise from a beginning. [6] And if that which is subsequent in
being or generation can come into being, so then can that which is antecedent; for instance, if a man can come into being, so can a child, for the child is antecedent; and similarly, if a child can come into being, so can a man, for the child is a beginning. [7] And things which we love or desire naturally are possible; for as a rule no one loves the impossible or desires it. [8] And those things which form the subject of sciences or arts can also exist and come into existence. [9] And so with all those things, the productive principles of which reside in those things which we can control by force or persuasion, when they depend upon those whose superiors, masters, or friends we are. [10] And if the parts are possible, so also is the whole; and if the whole is possible, so also are the parts, speaking generally; for instance, if the front, toe-cap, and upper leather,112 can be made, then shoes can be made, and if shoes, then the above parts. [11] And if the whole genus
is among things possible to be made, so is the species, and if the species, so the genus; for example, if a vessel can be built, so can a trireme, if a trireme can, so can a vessel. [12] If of two naturally corresponding things one is possible, so also is the other; for instance, if the double is possible, so is the half, if the half, so the double. [13] If a thing can be made without art or preparation, much the more can it be made with the help of art and carefulness. Whence it was said by Agathon113: “ And moreover we have to do some things by art, while others fall to our lot by compulsion or chance.

” [14] And if a thing is possible for those who are inferior, or weaker, or less intelligent, it will be still more so for those whose qualities are the opposite; as Isocrates said, it would be very strange if he were unable by himself to find out what Euthynus had learnt [with the help of others]. [15] As for the impossible, it is clear that there is a supply of arguments to be derived from the opposite of what has been said about the possible.

[16] The question whether a thing has or has not happened must be considered from the following points of view. [17] In the first place, if that which is naturally less likely has happened, then that which is more likely will most probably have happened. If that which usually happens afterwards has happened, then that which precedes must also have happened; for instance, if a man has forgotten a thing, he must once have learnt it. [18] If a man was able and wished to do a thing, he has done it; for all men
do a thing, when they are able and resolve to do it, for nothing hinders them. [19] Further, if a man wished to do it and there was no external obstacle; if he was able to do it and was in a state of anger; if he was able and desired to do it; for men as a rule, whenever they can, do those things which they long for, the vicious owing to want of self-control, the virtuous because they desire what is good. [20] And if anything was on the point of being done, it most probably was done; for it is likely that one who was on the point of doing something has carried it out. [21] And if all the natural antecedents or causes of a thing have happened; for instance, if it has lightened, it has also thundered; and if a man has already attempted a crime, he has also committed it. And if all the natural consequences or motives of actions have happened, then the antecedent or the cause has happened; for instance, if it has thundered, it has also lightened, and if a man has committed a crime, he has also attempted it. [22] Of all these things some are so related necessarily, others only as a general rule. To establish that a thing has not happened, it is evident that our argument must be derived from the opposite of what has been said.

[23] In regard to the future, it is clear that one can argue in the same way; for if we are able and wish to do a thing, it will be done; and so too will those things which desire, anger, and reasoning urge us to do, if we have the power. For this reason also, if a man has an eager desire, or intention, of doing a thing, it will probably be done; since, as a rule, things that are about to happen are more likely to happen than those which are not. [24] And if all the natural antecedents have happened; for instance, if the sky is cloudy, it will probably rain. [25] And if one thing has been done with a view to another, it is probable that the latter will also be done; for instance, if a foundation has been laid, a house will probably be built.

[26] What we have previously said clearly shows the nature of the greatness and smallness of things, of the greater and less, and of things great and small generally. For, when treating of deliberative rhetoric,114 we spoke of greatness of goods, and of the greater and less generally. Therefore, since in each branch of Rhetoric the end set before it is a good, such as the expedient, the noble, or the just, it is evident that all must take the materials of amplification from these. [27] To make any further inquiry as to magnitude and superiority absolutely would be waste of words; for the particular has more authority than the general for practical purposes.
Let this suffice for the possible and impossible; for the question whether a thing has happened, or will happen, or not; and for the greatness or smallness of things.

20. It remains to speak of the proofs common to all branches of Rhetoric, since the particular proofs have been discussed. These common proofs are of two kinds, example and enthymeme （for the maxim is part of an enthymeme）. [2] Let us then first speak of the example; for the example resembles induction, and induction is a beginning.115

There are two kinds of examples; namely, one which consists in relating things that have happened before, and another in inventing them oneself. The latter are subdivided into comparisons or fables, [3] such as those of Aesop and the Libyan.116 It would be an instance of the historical kind of example, if one were to say that it is necessary to make preparations against the Great King and not to allow him to subdue Egypt; for Darius did not cross over to Greece until he had obtained possession of Egypt;
but as soon as he had done so, he did. Again, Xerxes did not attack us until he had obtained possession of that country, but when he had, he crossed over; consequently, if the present Great King shall do the same, he will cross over, wherefore it must not be allowed. [4] Comparison is illustrated by the sayings of Socrates; for instance, if one were to say that magistrates should not be chosen by lot, for this would be the same as choosing as representative athletes not those competent to contend, but those on whom the lot falls; or as choosing any of the sailors as the man who should take the helm, as if it were right that the choice should be decided by lot, not by a man's knowledge.117

[5] A fable, to give an example, is that of Stesichorus concerning Phalaris, or that of Aesop on behalf of the demagogue. For Stesichorus, when the people of Himera had chosen Phalaris dictator and were on the point of giving him a body-guard, after many arguments related a fable to them: “A horse was in sole occupation of a meadow. A stag having come and done much damage to the pasture, the horse, wishing to avenge himself on the stag, asked a man whether he could help him to punish the stag. The man consented, on condition that the horse submitted to the bit and allowed him to mount him javelins in hand. The horse agreed to the terms and the man mounted him, but instead of obtaining vengeance on the stag, the horse from that time became the man's slave. So then,” said he, “do you take care lest, in your desire to avenge yourselves on the enemy,
you be treated like the horse. You already have the bit, since you have chosen a dictator; if you give him a body-guard and allow him to mount you, you will at once be the slaves of Phalaris.” [6] Aesop, when defending at Samos a demagogue who was being tried for his life, related the following anecdote. “A fox, while crossing a river, was driven into a ravine. Being unable to get out, she was for a long time in sore distress, and a number of dog-fleas clung to her skin. A hedgehog, wandering about, saw her and, moved with compassion, asked her if he should remove the fleas. The fox refused and when the hedgehog asked the reason, she answered: ‘They are already full of me and draw little blood; but if you take them away, others will come that are hungry and will drain what remains to me.’ You in like manner, O Samians, will suffer no more harm from this man, for he is wealthy; but if you put him to death,
others will come who are poor, who will steal and squander your public funds.” [7] Fables are suitable for public speaking, and they have this advantage that, while it is difficult to find similar things that have really happened in the past, it is easier to invent fables; for they must be invented, like comparisons, if a man is capable of seizing the analogy; and this is easy if one studies philosophy.118 [8] Thus, while the lessons conveyed by fables are easier to provide, those derived from facts are more useful for deliberative oratory, because as a rule the future resembles the past.

[9] If we have no enthymemes, we must employ examples as demonstrative proofs, for conviction is produced by these; but if we have them, examples must be used as evidence and as a kind of epilogue to the enthymemes.119 For if they stand first, they resemble induction, and induction is not suitable to rhetorical speeches except in very few cases; if they stand last they resemble evidence, and a witness is in every case likely to induce belief. Wherefore also it is necessary to quote a number of examples if they are put first, but one alone is sufficient if they are put last; for even a single trustworthy witness is of use. We have thus stated how many kinds of examples there are, and how and when they should be made use of.

21. In regard to the use of maxims, it will most readily be evident
on what subjects, and on what occasions, and by whom it is appropriate that maxims should be employed in speeches, after a maxim has been defined. [2] Now, a maxim is a statement, not however concerning particulars, as, for instance, what sort of a man Iphicrates was, but general; it does not even deal with all general things, as for instance that the straight is the opposite of the crooked, but with the objects of human actions, and with what should be chosen or avoided with reference to them. And as the enthymeme is, we may say,120 the syllogism dealing with such things, maxims are the premises or conclusions of enthymemes without the syllogism. For example: “ No man who is sensible ought to have his children taught to be excessively clever,121

” is a maxim; but when the why and the wherefore are added, the whole makes an enthymeme; for instance, “ for, not to speak of the charge of idleness brought against them,122 they earn jealous hostility from the citizens.

”
Another example: “ There is no man who is happy in everything;123

” or, “ There is no man who is really free.

” The latter is a maxim, but taken with the next verse it is an enthymeme: “ for he is the slave of either wealth or fortune.124

” [3] Now, if a maxim is what we have stated, it follows that maxims are of four kinds; for they are either accompanied by an epilogue or not.125 [4] Now all those that state anything that is contrary to the general opinion or is a matter of dispute, need demonstrative proof; but those that do not, need no epilogue,126 [5] either because they are already known, as, for instance, “ Health is a most excellent thing for a man, at least in our opinion,127

” for this is generally agreed; or because, no sooner are they uttered than they are clear to those who consider them, for instance, “ He is no lover who does not love always.128

” [6] As for the maxims that are accompanied by an epilogue, some form part of an enthymeme, as “ No one who is sensible, etc.,129

”
while others are enthymematic, but are not part of an enthymeme;130 and these are most highly esteemed. Such are those maxims in which the reason of what is said is apparent: for instance, “ Being a mortal, do not nourish immortal wrath;131

” to say that one should not always nourish immortal wrath is a maxim, but the addition “being a mortal” states the reason. It is the same with “ A mortal should have mortal, not immortal thoughts.132

”

[7] It is evident, therefore, from what has been said, how many kinds of maxims there are, and to what it is appropriate to apply them in each case. For in the case of matters of dispute or what is contrary to the general opinion, the epilogue is necessary; but either the epilogue may be put first and the conclusion used as a maxim, as, for example, if one were to say, “As for me, since one ought neither to be the object of jealousy nor to be idle, I say that children ought not to be educated”; or put the maxim first and append the epilogue. In all cases where the statements made, although not paradoxical, are obscure, the reason should be added as concisely as possible. [8] In such cases Laconic apophthegms and riddling sayings are suitable;
as, for instance, to say what Stesichorus said to the Locrians, that they ought not to be insolent, lest their cicadas should be forced to chirp from the ground.133 [9] The use of maxims is suitable for one who is advanced in years, and in regard to things in which one has experience; since the use of maxims before such an age is unseemly, as also is story-telling; and to speak about things of which one has no experience shows foolishness and lack of education. A sufficient proof of this is that rustics especially are fond of coining maxims and ready to make display of them.

[10] To express in general terms what is not general is especially suitable in complaint or exaggeration, and then either at the beginning or after the demonstration. [11] One should even make use of common and frequently quoted maxims, if they are useful; for because they are common, they seem to be true, since all as it were acknowledge them as such; for instance, one who is exhorting his soldiers to brave danger before having sacrificed may say, “ The best of omens is to defend one's country,134

” and if they are inferior in numbers, “ The chances of war are the same for both,135

” and if advising them to destroy the children of the enemy even though they are innocent of wrong, “ Foolish is he who, having slain the father, suffers the children to live.136

”

[12] Further, some proverbs are also maxims; for example,
“An Attic neighbor.”137 [13] Maxims should also be used even when contrary to the most popular sayings, such as “Know thyself” and “Nothing in excess,” either when one's character is thereby likely to appear better, or if they are expressed in the language of passion. It would be an instance of the latter if a man in a rage were to say, “It is not true that a man should know himself; at any rate, such a man as this, if he had known himself, would never have claimed the chief command.” And one's character would appear better, if one were to say that it is not right, as men say, to love as if one were bound to hate, but rather to hate as if one were bound to love. [14] The moral purpose also should be made clear by the language, or else one should add the reason; for example, either by saying “that it is right to love, not as men say, but as if one were going to love for ever, for the other kind of love would imply treachery”; or thus, “The maxim does not please me, for the true friend should love as if he were going to love for ever. Nor do I approve the maxim ‘Nothing in excess,’ for one cannot hate the wicked too much.”

[15] Further, maxims are of great assistance to speakers, first, because of the vulgarity138 of the hearers, who are pleased if an orator, speaking generally, hits upon the opinions which they specially hold.139 What I mean will be clear from the following, and also how one should hunt for maxims. The maxim, as we have said, is a statement of the general; accordingly, the hearers are pleased to hear stated in general terms the opinion which they have already specially formed. For instance, a man who happened to have bad neighbors or children would welcome any one's statement that nothing is more troublesome than neighbors or more stupid than to beget children. Wherefore the speaker should endeavor to guess how his hearers formed their preconceived opinions and what they are, and then express himself in general terms in regard to them. [16] This is one of the advantages of the use of maxims, but another is greater; for it makes speeches ethical. Speeches have this character, in which the moral purpose is clear. And this is the effect of all maxims, because he who employs them in a general manner declares his moral preferences; if then the maxims are good, they show the speaker also to be a man of good character. Let this suffice for what we had to say concerning maxims, their nature, how many kinds of them there are, the way they should be used, and what their advantages are.

22. Let us now speak of enthymemes in general and the manner of looking for them, and next of their topics; for each of these things is different in kind. [2] We have already said that the enthymeme is a kind of syllogism, what makes it so, and in what it differs from the dialectic syllogisms; [3] for the conclusion must neither be drawn from too far back140 nor should it include all the steps of the argument. In the first case its length causes obscurity, in the second, it is simply a waste of words, because it states much that is obvious. It is this that makes the ignorant more persuasive than the educated in the presence of crowds; as the poets say, “the ignorant are more skilled at speaking before a mob.”141 For the educated use commonplaces and generalities, whereas the ignorant speak of what they know and of what more nearly concerns the audience. Wherefore one must not argue from all possible opinions, but only from such as are definite and admitted, for instance, either by the judges themselves or by those of whose judgement they approve.
Further, it should be clear that this is the opinion of all or most of the hearers; and again, conclusions should not be drawn from necessary premises alone, but also from those which are only true as a rule.

[4] First of all, then, it must be understood that, in regard to the subject of our speech or reasoning, whether it be political or of any other kind, it is necessary to be also acquainted with the elements of the question, either entirely or in part; for if you know none of these things, you will have nothing from which to draw a conclusion. [5] I should like to know, for instance, how we are to give advice to the Athenians as to making war or not, if we do not know in what their strength consists, whether it is naval, military, or both, how great it is, their sources of revenue, their friends and enemies, and further, what wars they have already waged, with what success, and all similar things? [6] Again, how could we praise them, if we did not know of the naval engagement at Salamis or the battle of Marathon, or what they did for the Heraclidae, and other similar things? for men always base their praise upon what really are, or are thought to be, glorious deeds. [7] Similarly, they base their censure upon actions that are contrary to these, examining whether those censured have really, or seem to have, committed them; for example, that the Athenians subjugated the Greeks, and reduced to slavery the Aeginetans and Potidaeans
who had fought with distinction on their side against the barbarians, and all such acts, and whatever other similar offences may have been committed by them. Similarly, in accusation and defence, speakers argue from an examination of the circumstances of the case. [8] It makes no difference in doing this, whether it is a question of Athenians or Lacedaemonians, of a man or a god. For, when advising Achilles, praising or censuring, accusing or defending him, we must grasp all that really belongs, or appears to belong to him, in order that we may praise or censure in accordance with this, if there is anything noble or disgraceful; defend or accuse, if there is anything just or unjust; advise, if there is anything expedient or harmful. [9] And similarly in regard to any subject whatever. For instance, in regard to justice, whether it is good or not, we must consider the question in the light of what is inherent in justice or the good.

[10] Therefore, since it is evident that all men follow this procedure in demonstration, whether they reason strictly
or loosely—since they do not derive their arguments from all things indiscriminately, but from what is inherent in each particular subject, and reason makes it clear that it is impossible to prove anything in any other way142—it is evidently necessary, as has been stated in the Topics,143 to have first on each subject a selection of premises about probabilities and what is most suitable. [11] As for those to be used in sudden emergencies, the same method of inquiry must be adopted; we must look, not at what is indefinite but at what is inherent in the subject treated of in the speech, marking off as many facts as possible, particularly those intimately connected with the subject; for the more facts one has, the easier it is to demonstrate, and the more closely connected they are with the subject, the more suitable are they and less common.144 [12] By common I mean, for instance, praising Achilles because he is a man, or one of the demigods, or because he went on the expedition against Troy; for this is applicable to many others as well, so that such praise is no more suited to Achilles than to Diomedes. By particular I mean what belongs to Achilles, but to no one else; for instance, to have slain Hector, the bravest of the Trojans, and Cycnus, who prevented all the Greeks from disembarking, being invulnerable; to have gone to the war when very young, and without having taken the oath; and all such things.

[13] One method of selection then, and this the first, is the topical.
Let us now speak of the elements of enthymemes （by element and topic of enthymeme I mean the same thing）. But let us first make some necessary remarks. [14] There are two kinds of enthymemes, the one demonstrative, which proves that a thing is or is not, and the other refutative, the two differing like refutation and syllogism in Dialectic. [15] The demonstrative enthymeme draws conclusions from admitted premises, the refutative draws conclusions disputed by the adversary.145 [16] We know nearly all the general heads of each of the special topics that are useful or necessary; for the propositions relating to each have been selected, so that we have in like manner already established all the topics from which enthymemes may be derived on the subject of good or bad, fair or foul, just or unjust, characters, emotions, and habits.
[17] Let us now endeavor to find topics about enthymemes in general in another way, noting in passing146 those which are refutative and those which are demonstrative, and those of apparent enthymemes, which are not really enthymemes, since they are not syllogisms. After this has been made clear, we will settle the question of solutions and objections, and whence they must be derived to refute enthymemes.

23. One topic of demonstrative enthymemes is derived from opposites; for it is necessary to consider whether one opposite is predicable of the other, as a means of destroying an argument, if it is not, as a means of constructing one, if it is;147 for instance, self-control is good, for lack of self-control is harmful; or as in the Messeniacus,148 “If the war is responsible for the present evils, one must repair them with the aid of peace.” And, “ For if it is unfair to be angry with those who have done wrong unintentionally, it is not fitting to feel beholden to one who is forced to do us good.149

” Or, “ If men are in the habit of gaining credit for false statements, you must also admit the contrary, that men often disbelieve what is true.150

”

[2] Another topic is derived from similar inflections, for in like manner the derivatives must either be predicable of the subject or not; for instance, that the just is not entirely good, for in that case good would be predicable of anything that happens justly; but to be justly put to death is not desirable.

[3] Another topic is derived from relative terms. For if to have done rightly or justly may be predicated of one, then to have suffered similarly may be predicated of the other; there is the same relation between having ordered and having carried out, as Diomedon the tax-gatherer said about the taxes, “If selling is not disgraceful for you, neither is buying disgraceful for us.”151 And if rightly or justly can be predicated of the sufferer, it can equally be predicated of the one who inflicts suffering; if of the latter, then also of the former. However, in this there is room for a fallacy. For if a man has suffered justly, he has suffered justly, but perhaps not at your hands. Wherefore one must consider separately whether the sufferer deserves to suffer,
and whether he who inflicts suffering is the right person to do so, and then make use of the argument either way; for sometimes there is a difference in such a case, and nothing prevents [its being argued], as in the Alcmaeon of Theodectes152: “ And did no one of mortals loathe thy mother?

” Alcmaeon replied: “We must make a division before we examine the matter.” And when Alphesiboea asked “How?”, he rejoined, “ Their decision was that she should die, but that it was not for me to kill her.

” Another example may be found in the trial of Demosthenes and those who slew Nicanor.153 For since it was decided that they had justly slain him, it was thought that he had been justly put to death. Again, in the case of the man who was murdered at Thebes, when the defendants demanded that the judges should decide whether the murdered man deserved to die, since a man who deserved it could be put to death without injustice.

[4] Another topic is derived from the more and less. For instance, if not even the gods know everything, hardly can men; for this amounts to saying that if a predicate, which is more probably affirmable of one thing, does not belong to it, it is clear that it does not belong to another of which it is less probably affirmable. And to say that a man who beats his father also beats his neighbors, is an instance of the rule that, if the less exists, the more also exists.154 Either of these arguments may be used, according as it is necessary to prove either that a predicate is affirmable or that it is not. [5] Further, if
there is no question of greater or less; whence it was said, “ Thy father deserves to be pitied for having lost his children; is not Oeneus then equally to be pitied for having lost an illustrious offspring?155

” Other instances are: if Theseus did no wrong,156 neither did Alexander Paris; if the sons of Tyndareus did no wrong, neither did Alexander; and if Hector did no wrong in slaying Patroclus, neither did Alexander in slaying Achilles; if no other professional men are contemptible, then neither are philosophers; if generals are not despised because they are frequently defeated,157 neither are the sophists; or, if it behoves a private citizen to take care of your reputation, it is your duty to take care of that of Greece.

[6] Another topic is derived from the consideration of time. Thus Iphicrates, in his speech against Harmodius, says: “If, before accomplishing anything, I had demanded the statue from you in the event of my success, you would have granted it; will you then refuse it, now that I have succeeded? Do not therefore make a promise when you expect something, and break it when you have received it.”158 Again, to persuade the Thebans to allow Philip to pass through their territory into Attica,
they were told that “if he had made this request before helping them against the Phocians, they would have promised; it would be absurd, therefore, if they refused to let him through now, because he had thrown away his opportunity and had trusted them.”

[7] Another topic consists in turning upon the opponent what has been said against ourselves; and this is an excellent method.159 For instance, in the Teucer160 . . . and Iphicrates employed it against Aristophon, when he asked him whether he would have betrayed the fleet for a bribe; when Aristophon said no, “Then,” retorted Iphicrates, “if you, Aristophon, would not have betrayed it, would I, Iphicrates, have done so?” But the opponent must be a man who seems the more likely to have committed a crime; otherwise, it would appear ridiculous, if anyone were to make use of such an argument in reference to such an opponent, for instance, as Aristides161; it should only be used to discredit the accuser. For in general the accuser aspires to be better than the defendant; accordingly, it must always be shown that this is not the case. And generally, it is ridiculous for a man to reproach others for what he does or would do himself, or to encourage others to do what he does not or would not do himself.

[8] Another topic is derived from definition. For instance, that the daimonion162 is nothing else than a god or the work of a god; but he who thinks it to be the work of a god necessarily thinks that gods exist. When Iphicrates desired to prove that the best man is the noblest, he declared that there was nothing noble attaching to Harmodius and Aristogiton, before they did something
noble; and, “I myself am more akin to them than you; at any rate, my deeds are more akin to theirs than yours.” And as it is said in the Alexander163 that it would be generally admitted that men of disorderly passions are not satisfied with the enjoyment of one woman's person alone. Also, the reason why Socrates refused to visit Archelaus, declaring that it was disgraceful not to be in a position to return a favor as well as an injury.164 In all these cases, it is by definition and the knowledge of what the thing is in itself that conclusions are drawn upon the subject in question.

[9] Another topic is derived from the different significations of a word, as explained in the Topics, where the correct use of these terms has been discussed.165

[10] Another, from division. For example, “There are always three motives for wrongdoing; two are excluded from consideration as impossible; as for the third, not even the accusers assert it.”

[11] Another, from induction. For instance, from the case of the woman of Peparethus, it is argued that in matters of parentage women always discern the truth;
similarly, at Athens, when Mantias the orator was litigating with his son, the mother declared the truth;166 and again, at Thebes, when Ismenias and Stilbon were disputing about a child, Dodonis167 declared that Ismenias was its father, Thettaliscus being accordingly recognized as the son of Ismenias. There is another instance in the “law” of Theodectes: “If we do not entrust our own horses to those who have neglected the horses of others, or our ships to those who have upset the ships of others; then, if this is so in all cases, we must not entrust our own safety to those who have failed to preserve the safety of others.” Similarly, in order to prove that men of talent are everywhere honored, Alcidamas said: “The Parians honored Archilochus, in spite of his evil-speaking; the Chians Homer, although he had rendered no public services;168 the Mytilenaeans Sappho, although she was a woman; the Lacedaemonians, by no means a people fond of learning, elected Chilon one of their senators; the Italiotes honored Pythagoras, and the Lampsacenes buried Anaxagoras, although he was a foreigner, and still hold him in honor. . .169 The Athenians were happy as long as they lived under the laws of Solon, and the Lacedaemonians under those of Lycurgus; and at Thebes, as soon as those who had the conduct of affairs became philosophers,170
the city flourished.”

[12] Another topic is that from a previous judgement in regard to the same or a similar or contrary matter, if possible when the judgement was unanimous or the same at all times; if not, when it was at least that of the majority, or of the wise, either all or most, or of the good; or of the judges themselves or of those whose judgement they accept, or of those whose judgement it is not possible to contradict, for instance, those in authority, or of those whose judgement it is unseemly to contradict, for instance, the gods, a father, or instructors; as Autocles171 said in his attack on Mixidemides, “If the awful goddesses were content to stand their trial before the Areopagus, should not Mixidemides?” Or Sappho, “Death is an evil; the gods have so decided, for otherwise they would die.” Or as Aristippus, when in his opinion Plato had expressed himself too presumptuously, said, “Our friend at any rate never spoke like that,” referring to Socrates. Hegesippus,172 after having first consulted the oracle at Olympia, asked the god at Delphi whether his opinion was the same as his father's,
meaning that it would be disgraceful to contradict him. Helen was a virtuous woman, wrote Isocrates, because Theseus so judged; the same applies to Alexander Paris, whom the goddesses chose before others. Evagoras was virtuous, as Isocrates says, for at any rate Conon.173 in his misfortune, passing over everyone else, sought his assistance.

[13] Another topic is that from enumerating the parts, as in the Topics: What kind of movement is the soul? for it must be this or that.174 There is an instance of this in the Socrates of Theodectes: “What holy place has he profaned? Which of the gods recognized by the city has he neglected to honor?”

[14] Again, since in most human affairs the same thing is accompanied by some bad or good result, another topic consists in employing the consequence to exhort or dissuade, accuse or defend, praise or blame. For instance, education is attended by the evil of being envied, and by the good of being wise; therefore we should not be educated, for we should avoid being envied; nay rather, we should be educated, for we should be wise. This topic is identical with the “Art” of Callippus, when you have also included the topic of the possible and the others which have been mentioned.

[15] Another topic may be employed when it is necessary to exhort or dissuade
in regard to two opposites, and one has to employ the method previously stated in the case of both. But there is this difference, that in the former case things of any kind whatever are opposed, in the latter opposites. For instance, a priestess refused to allow her son to speak in public; “For if,” said she, “you say what is just, men will hate you; if you say what is unjust, the gods will.” On the other hand, “you should speak in public; for if you say what is just, the gods will love you, if you say what is unjust, men will.” This is the same as the proverb, “To buy the swamp with the salt”175; and retorting a dilemma on its proposer takes place when, two things being opposite, good and evil follow on each, the good and evil being opposite like the things themselves.

[16] Again, since men do not praise the same things in public and in secret, but in public chiefly praise what is just and beautiful, and in secret rather wish for what is expedient, another topic consists in endeavoring to infer its opposite from one or other of these statements.176 This topic is the most weighty of those that deal with paradox.

[17] Another topic is derived from analogy in things. For instance, Iphicrates, when they tried to force his son to perform public services because he was tall, although under the legal age, said: “If you consider tall boys men, you must vote that short men are boys.”
Similarly, Theodectes in his “law,”177 says: “Since you bestow the rights of citizenship upon mercenaries such as Strabax and Charidemus on account of their merits, will you not banish those of them who have wrought such irreparable misfortunes?”

[18] Another topic consists in concluding the identity of antecedents from the identity of results.178 Thus Xenophanes said: “There is as much impiety in asserting that the gods are born as in saying that they die; for either way the result is that at some time or other they did not exist.” And, generally speaking, one may always regard as identical the results produced by one or other of any two things: “You are about to decide, not about Isocrates alone, but about education generally, whether it is right to study philosophy.”179 And, “to give earth and water is slavery,” and “to be included in the common peace180 implies obeying orders.” Of two alternatives, you should take that which is useful.

[19] Another topic is derived from the fact that the same men do not always choose the same thing before and after, but the contrary. The following enthymeme is an example: “If, when in exile, we fought to return to our country [it would be monstrous] if, now that we have returned, we were to return to exile to avoid fighting”!181 This amounts to saying that at one time they preferred to hold their ground at the price of fighting; at another, not to fight at the price of not remaining.182

[20] Another topic consists in maintaining that the cause of something which is or has been is something which would generally, or possibly might, be the cause of it; for example, if one were to make a present of something to another, in order to cause him pain by depriving him of it. Whence it has been said: “ It is not from benevolence that the deity bestows great blessings upon many, but in order that they may suffer more striking calamities.183

” And these verses from the Meleager of Antiphon: “ Not in order to slay the monster, but that they may be witnesses to Greece of the valor of Meleager.184

” And the following remark from the Ajax of Theodectes, that Diomedes chose Odysseus before all others,185 not to do him honor, but that his companion might be his inferior; for this may have been the reason.

[21] Another topic common to forensic and deliberative rhetoric consists in examining what is hortatory and dissuasive, and the reasons which make men act or not. Now, these are the reasons which, if they exist, determine us to act, if not, not; for instance, if a thing is possible, easy, or useful to ourselves or our friends, or injurious and prejudicial to our enemies, or if the penalty is less than the profit. From these grounds we exhort, and dissuade from their contraries.
It is on the same grounds that we accuse and defend; for what dissuades serves for defence,186 what persuades, for accusation. This topic comprises the whole “Art” of Pamphilus and Callippus.

[22] Another topic is derived from things which are thought to happen but are incredible, because it would never have been thought so, if they had not happened or almost happened. And further, these things are even more likely to be true; for we only believe in that which is, or that which is probable: if then a thing is incredible and not probable, it will be true; for it is not because it is probable and credible that we think it true.187 Thus, Androcles188 of Pitthus, speaking against the law, being shouted at when he said “the laws need a law to correct them,” went on, “and fishes need salt, although it is neither probable nor credible that they should, being brought up in brine; similarly, pressed olives need oil, although it is incredible that what produces oil should itself need oil.”

[23] Another topic, appropriate to refutation, consists in examining contradictories, whether in dates, actions, or words, first, separately in the case of the adversary, for instance, “he says that he loves you, and yet he conspired with the Thirty;” next, separately in your own case, “he says that I am litigious, but he cannot
prove that I have ever brought an action against anyone”; lastly, separately in the case of your adversary and yourself together: “he has never yet lent anything, but I have ransomed many of you.”

[24] Another topic, when men or things have been attacked by slander, in reality or in appearance,189 consists in stating the reason for the false opinion; for there must be a reason for the supposition of guilt. For example, a woman embraced her son in a manner that suggested she had illicit relations with him, but when the reason was explained, the slander was quashed. Again, in the Ajax of Theodectes, Odysseus explains to Ajax why, although really more courageous than Ajax, he is not considered to be so.

[25] Another topic is derived from the cause. If the cause exists, the effect exists; if the cause does not exist, the effect does not exist; for the effect exists with the cause, and without cause there is nothing. For example, Leodamas, when defending himself against the accusation of Thrasybulus that his name had been posted in the Acropolis190 but that he had erased it in the time of the Thirty, declared that it was impossible, for the Thirty would have had more confidence in him if his hatred against the people had been graven on the stone.

[26] Another topic consists in examining whether there was or is another better course than that which is advised, or is being, or has been, carried out. For it is evident that,
if this has not been done,191 a person has not committed a certain action; because no one, purposely or knowingly, chooses what is bad. However, this argument may be false; for often it is not until later that it becomes clear what was the better course, which previously was uncertain.

[27] Another topic, when something contrary to what has already been done is on the point of being done, consists in examining them together. For instance, when the people of Elea asked Xenophanes if they ought to sacrifice and sing dirges to Leucothea,192 or not, he advised them that, if they believed her to be a goddess they ought not to sing dirges, but if they believed her to be a mortal, they ought not to sacrifice to her.

[28] Another topic consists in making use of errors committed, for purposes of accusation or defence. For instance, in the Medea of Carcinus,193 some accuse Medea of having killed her children,—at any rate, they had disappeared; for she had made the mistake of sending them out of the way. Medea herself pleads that she would have slain, not her children, but her husband Jason; for it would have been a mistake on her part not to have done this, if she had done the other. This topic and kind of enthymeme is the subject of the whole of the first “Art” of Theodorus.194

[29] Another topic is derived from the meaning of a name. For instance, Sophocles says, “ Certainly thou art iron, like thy name.195

” This topic is also commonly employed in praising the gods.
Conon used to call Thrasybulus “the man bold in counsel,” and Herodicus said of Thrasymachus, “Thou art ever bold in fight,” and of Polus, “Thou art ever Polus （colt） by name and colt by nature,”196 and of Draco the legislator that his laws were not those of a man, but of a dragon, so severe were they. Hecuba in Euripides197 speaks thus of Aphro-dite: “ And rightly does the name of the goddess begin like the word aphro-syne （folly）;

” and Chaeremon198 of Pentheus, “ Pentheus named after his unhappy future.

”

[30] Enthymemes that serve to refute are more popular than those that serve to demonstrate, because the former is a conclusion of opposites199 in a small compass, and things in juxtaposition are always clearer to the audience. But of all syllogisms, whether refutative or demonstrative, those are specially applauded, the result of which the hearers foresee as soon as they are begun, and not because they are superficial （for as they listen they congratulate themselves on anticipating the conclusion）; and also those which the hearers are only so little behind that they understand what they mean as soon as they are delivered.

24. But as it is possible that some syllogisms may be real, and others not real but only apparent, there must also be real and apparent enthymemes, since the enthymeme is a kind of syllogism.

[2] Now, of the topics of apparent enthymemes one is that of diction, which is of two kinds. The first, as in Dialectic, consists in ending with a conclusion syllogistically expressed, although there has been no syllogistic process, “therefore it is neither this nor that,” “so it must be this or that”; and similarly in rhetorical arguments a concise and antithetical statement is supposed to be an enthymeme; for such a style appears to contain a real enthymeme. This fallacy appears to be the result of the form of expression. For the purpose of using the diction to create an impression of syllogistic reasoning it is useful to state the heads of several syllogisms: “He saved some, avenged others, and freed the Greeks”;200 for each of these propositions has been proved by others, but their union appears to furnish a fresh conclusion.

The second kind of fallacy of diction is homonymy.201 For instance, if one were to say that the mouse is an important animal, since from it is derived the most honored of all religious festivals, namely, the mysteries202; or if, in praising the dog, one were to include the dog in heaven （Sirius）, or Pan, because Pindar said,203 “ O blessed one, whom the Olympians call dog of the Great Mother, taking every form,

”
or were to say that the dog is an honorable animal, since to be without a dog is most dishonorable. And to say that Hermes is the most sociable of the gods, because he alone is called common;204 and that words are most excellent, since good men are considered worthy, not of riches but of consideration; for λόγου ἄξιος has a double meaning.205

[3] Another fallacy consists in combining what is divided or dividing what is combined. For since a thing which is not the same as another often appears to be the same, one may adopt the more convenient alternative. Such was the argument of Euthydemus, to prove, for example, that a man knows that there is a trireme in the Piraeus, because he knows the existence of two things, the Piraeus and the trireme;206 or that, when one knows the letters, one also knows the word made of them, for word and letters are the same thing. Further, since twice so much is unwholesome, one may argue that neither is the original amount wholesome; for it would be absurd that two halves separately should be good, but bad combined. In this way the argument may be used for refutation, in another way for demonstration, if one were to say, one good thing cannot make two bad things. But the whole topic is fallacious. Again, one may quote what Polycrates said of Thrasybulus, that he deposed thirty tyrants,207 for here he combines them; or the example of the fallacy of division in the Orestes of Theodectes:208 “It is just that a woman who has killed her husband” should be put to death, and that the son should avenge the father;
and this in fact is what has been done. But if they are combined, perhaps the act ceases to be just. The same might also be classed as an example of the fallacy of omission; for the name of the one who should put the woman to death is not mentioned.

[4] Another topic is that of constructing or destroying by exaggeration, which takes place when the speaker, without having proved that any crime has actually been committed, exaggerates the supposed fact; for it makes it appear either that the accused is not guilty, when he himself exaggerates it, or that he is guilty, when it is the accuser who is in a rage. Therefore there is no enthymeme; for the hearer falsely concludes that the accused is guilty or not, although neither has been proved.

[5] Another fallacy is that of the sign, for this argument also is illogical. For instance, if one were to say that those who love one another are useful to States, since the love of Harmodius and Aristogiton overthrew the tyrant Hipparchus; or that Dionysius is a thief, because he is a rascal; for here again the argument is inconclusive; not every rascal is a thief although every thief is a rascal.

[6] Another fallacy is derived from accident; for instance, when Polycrates says of the mice, that, they rendered great service by gnawing the bowstrings.209 Or if one were to say that nothing is more honorable than to be invited to a dinner, for because he was not invited Achilles was angry with the Achaeans at Tenedos; whereas he was really angry because he had been treated with disrespect, but this was an accident due to his not having been invited.210

[7] Another fallacy is that of the Consequence.211 For instance, in the Alexander Paris it is said that Paris was high-minded, because he despised the companionship of the common herd and dwelt on Ida by himself; for because the high-minded are of this character, Paris also might be thought high-minded. Or, since a man pays attention to dress and roams about at night, he is a libertine, because libertines are of this character. Similarly, the poor sing and dance in the temples, exiles can live where they please; and since these things belong to those who are apparently happy, those to whom they belong may also be thought happy. But there is a difference in conditions;212 wherefore this topic also falls under the head of omission.

[8] Another fallacy consists of taking what is not the cause for the cause, as when a thing has happened at the same time as, or after, another; for it is believed that what happens after is produced by the other, especially by politicians. Thus, Demades declared that the policy of Demosthenes was the cause of all the evils that happened, since it was followed by the war.

[9] Another fallacy is the omission of when and how. For instance, Alexander Paris had a right to carry off Helen, for the choice of a husband had been given her by her father. But （this was a fallacy）, for it was not, as might be thought, for all time, but only for the first time; for the father's authority only lasts till then.
Or, if one should say that it is wanton outrage to beat a free man; for this is not always the case, but only when the assailant gives the first blow.

[10] Further, as in sophistical disputations, an apparent syllogism arises as the result of considering a thing first absolutely, and then not absolutely, but only in a particular case. For instance, in Dialectic, it is argued that that which is not is, for that which is not is that which is not213; also, that the unknown can be known, for it can be known of the unknown that it is unknown. Similarly, in Rhetoric, an apparent enthymeme may arise from that which is not absolutely probable but only in particular cases. But this is not to be understood absolutely, as Agathon says: “ One might perhaps say that this very thing is probable, that many things happen to men that are not probable;

” for that which is contrary to probability nevertheless does happen, so that that which is contrary to probability is probable. If this is so, that which is improbable will be probable. But not absolutely; but as, in the case of sophistical disputations, the argument becomes fallacious when the circumstances, reference, and manner are not added, so here it will become so owing to the probability being not probable absolutely but only in particular cases. [11] The “Art” of Corax is composed of this topic. For if a man is not likely to be guilty of what he is accused of, for instance if, being weak, he is accused of assault and battery, his defence will be that the crime is not probable; but if he is likely to be guilty, for instance,
if he is strong, it may be argued again that the crime is not probable, for the very reason that it was bound to appear so. It is the same in all other cases; for a man must either be likely to have committed a crime or not. Here, both the alternatives appear equally probable, but the one is really so, the other not probable absolutely, but only in the conditions mentioned. And this is what “making the worse appear the better argument” means. Wherefore men were justly disgusted with the promise of Protagoras214; for it is a lie, not a real but an apparent probability, not found in any art except Rhetoric and Sophistic. So much for real or apparent enthymemes.

25. Next to what has been said we must speak of refutation. An argument may be refuted either by a counter-syllogism215 or by bringing an objection. [2] It is clear that the same topics may furnish counter-syllogisms; for syllogisms are derived from probable materials and many probabilities are contrary to one another. [3] An objection is brought, as shown in the Topics, in four ways: it may be derived either from itself,216 or from what is similar, or from what is contrary, or from what has been decided. [4] In the first case, if for instance the enthymeme was intended to prove that love is good,
two objections might be made; either the general statement that all want217 is bad, or in particular, that Caunian love218 would not have become proverbial, unless some forms of love had been bad. [5] An objection from what is contrary is brought if, for instance, the enthymeme is that the good man does good to all his friends; it may be objected: But the bad man does not do harm [to all his friends].219 [6] An objection from what is similar is brought, if the enthymeme is that those who have been injured always hate, by arguing that those who have been benefited do not always love. [7] The fourth kind of objection is derived from the former decisions of well-known men. For instance, if the enthymeme is that one should make allowance for those who are drunk, for their offence is the result of ignorance, it may be objected that Pittacus then is unworthy of commendation, otherwise he would not have laid down severer punishment for a man who commits an offence when drunk.

[8] Now the material of enthymemes is derived from four sources—probabilities, examples, necessary signs, and signs. Conclusions are drawn from probabilities, when based upon things which most commonly occur or seem to occur; from examples, when they are the result of induction from one or more similar cases, and when one assumes the general and then concludes the particular by an example; from necessary signs, when based upon that which is necessary and ever220 exists; from signs, when their material is the general or
the particular, whether true or not. Now, the probable being not what occurs invariably but only for the most part, it is evident that enthymemes of this character can always be refuted by bringing an objection. [9] But the objection is often only apparent, not real; for he who brings the objection endeavors to show, not that the argument is not probable, but that it is not necessary. [10] Wherefore, by the employment of this fallacy, the defendant always has an advantage over the accuser. For since the latter always bases his proof upon probabilities, and it is not the same thing to show that an argument is not probable as to show that it is not necessary, and that which is only true for the most part is always liable to objection （otherwise it would not be probable, but constant and necessary）,—then the judge thinks, if the refutation is made in this manner,221 either that the argument is not probable, or that it is not for him to decide,222 being deceived by the fallacy, as we have just indicated. For his judgement must not rest upon necessary arguments alone, but also upon probabilities; for this is what is meant by deciding according to the best of one's judgement. It is therefore not enough to refute an argument by showing that it is not necessary; it must also be shown that it is not probable. This will be attained if the objection itself is specially based upon what happens generally. [11] This may take place in two ways, from consideration either of the time or of the facts.223 The strongest objections are those in which both are combined;
for a thing is more probable, the greater the number of similar cases.

[12] Signs and enthymemes based upon signs, even if true, may be refuted in the manner previously stated224; for it is clear from the Analytics225 that no sign can furnish a logical conclusion. [13] As for enthymemes derived from examples, they may be refuted in the same manner as probabilities. For if we have a single fact that contradicts the opponent's example, the argument is refuted as not being necessary, even though examples, more in number and of more common occurrence, are otherwise226; but if the majority and greater frequency of examples is on the side of the opponent, we must contend either that the present example is not similar to those cited by him, or that the thing did not take place in the same way, or that there is some difference. [14] But necessary signs and the enthymemes derived from them cannot be refuted on the ground of not furnishing a logical conclusion, as is clear from the Analytics227; the only thing that remains is to prove that the thing alleged is non-existent. But if it is evident that it is true and that it is a necessary sign, the argument at once becomes irrefutable; for, by means of demonstration, everything at once becomes clear.228

26. Amplification and depreciation are not elements of enthymeme （for I regard element and topic as identical）, since element （or topic） is a head under which several enthymemes are included, but they are enthymemes which serve to show that a thing is great or small,
just as others serve to show that it is good or bad, just or unjust, or anything else. [2] All these are the materials of syllogisms and enthymemes; so that if none of these is a topic of enthymeme, neither is amplification or depreciation. [3] Nor are enthymemes by which arguments are refuted of a different kind from those by which they are established; for it is clear that demonstration or bringing an objection is the means of refutation. By the first the contrary of the adversary's conclusion is demonstrated; for instance, if he has shown that a thing has happened, his opponent shows that it has not; if he has shown that a thing has not happened, he shows that it has. This, therefore, will not be the difference between them; for both employ the same arguments; they bring forward enthymemes to show that the thing is or that it is not. [4] And the objection is not an enthymeme, but, as I said in the Topics, it is stating an opinion which is intended to make it clear that the adversary's syllogism is not logical, or that he has assumed some false premise. [5] Now, since there are three things in regard to speech, to which special attention should be devoted, let what has been said suffice for examples, maxims, enthymemes, and what concerns the intelligence229 generally;
for the sources of a supply of arguments and the means of refuting them. It only remains to speak of style and arrangement.

1 This is Cope's interpretation. Jebb renders: “If we take each branch of Rhetoric by itself.” The classes are of course the deliberative, forensic, and epideictic.

2 The instructions given for enthymematic or logical proof should suffice; but since the function of Rhetoric is to find the available means of persuasion and its end is a judgement; and since an appeal to the speaker's own character and to the passions of those who are to give the judgement is bound to carry great weight, the speaker must be provided with rules for ethical and “pathetic” （emotional） proofs. In Book 1.5 Aristotle mentions appeals to the emotions with disapproval, but this does not apply to all such appeals, but only to those which are likely to bias the judges unfairly （e.g. stirring up envy, hatred, a desire for revenge）.

3 Opposed to εὐέλπιδι. Others render “in a bad humor.”

4 ἐπιεικής and σπουδαῖος both = ἀγαθός. In a restricted sense ἐπιεικής is “respectable,” σπουδαῖος “serious.”

5 See previous note.

6 Book 1.9.

7 In Book 1 generally （cp. 1.2.22）.

8 Gomperz translates φαινομένης “real or apparent”; Jebb omits φαινομένης and translates φαινομένην “apparent”; Cope confines both to the meaning “manifest.”

9 Hom. Il. 18.109 （cp. 1.11.9）.

10 The thought of revenge in the future, as distinguished from dwelling upon it in the present.

11 Or, “those in which this tendency does not exist, or is trifling.”

12 Or, “how to make him his friend,” φίλος being for φίλον by attraction.

13 In Attic law ὕβρις （insulting, degrading treatment） was a more serious offence than αἰκία （bodily ill-treatment）. It was the subject of a State criminal prosecution （ γραφή）, αἰκία of a private action （ δίκη） for damages. The penalty was assessed in court, and might even be death. It had to be proved that the defendant struck the first blow （2.24.9）. One of the best known instances is the action brought by Demosthenes against Midias for a personal outrage on himself, when choregus of his tribe and responsible for the equipment of a chorus for musical competitions at public festivals.

14 Hom. Il. 1.356.

15 Hom. Il. 9.648. μετανάστης, lit. “one who changes his home,” used as a term of reproach.

16 ταὐτῷ. Other readings are ταῦτα, or τις.

17 Hom. Il. 2.196.

18 Hom. Il. 1.82. The words are those of the soothsayer Calchas to Achilles, and the reference is to Agamemnon.

19 τοῖς πρὸς τὴν νόσον: lit. “the sick man [is angry with those who slight him] in regard to his illness,” that is, by making light of it.

20 Or, “his suffering at the moment.”

21 εὐκίνητοι refers grammatically to διαθέσεις and ἡλικίαι.

22 Plexippus was the uncle of Meleager. The allusion is obscure. It may refer to Meleager giving the skin of the Calydonian boar to Atalanta, which his uncle wanted. One of Antiphon's tragedies was named Meleager （T.G.F. p.792）.

23 Literally, “for the things which （= the persons whom） one respects, do not escape notice.”

24 The real friend, therefore, would feel as much pain as the other whose faults are exposed.

25 Cope translates “rulers and governors”; but can ἄρχεσθαι be used in a middle sense?

26 To avoid the apparent tautology （ 2.17）, Roemer （Rhein. Mus. 39 p. 503） boldly conjectures χαίρειν: “not to return another's greeting.”

27 ἐξαπίνης δ᾽ Ο᾿δυσῆα ἴδον κύνες ὑλακόμωποι: οἱ μὲν κεκλήγοντες ἐπέδραμον: αὐτὰρ Ο᾿δυσσεύς ἕζετο κερδοσύνῃ （Hom. Od. 14.29-31）.

28 That is, greater than their present disservices.

29 They regard the disrespectful treatment as merely a temporary lapse.

30 πλήρωσις: lit. “filling up.” The reference may be to the “fulfillment” of one's desires, or to “repletion” in the matter of food （L. and S.）, which seems less likely; “in fulness of content” （Jebb）.

31 Opponent of Demosthenes, and one of the pro-Macedonian party. Impeached for his share in the disastrous “Peace of Philocrates,” he went into exile and was condemned to death during his absence.

32 Ergophilus failed in an attack on Cotys, king of Thrace, while Callisthenes concluded a premature peace with Perdiccas, king of Macedonia.

33 Another reading is ἐὰν ἕλωσι, “if they have convicted him.” This is adopted by Roemer, who refers to Plat. Rep. 558a, where, in speaking of the freedom allowed to all who live under a democracy, it is remarked that, even if a man is convicted by a court of justice, he takes no heed of the sentence, which is very often not enforced.

34 Therefore, if you think that a man will never learn who took vengeance on him, you will be less cruel; for anger is personal, and so Odysseus, because he was angry, inflicted a savage punishment, and wished Polyphemus to know it.

35 Hom. Od. 9.504.

36 Or, “as if Odysseus would not have considered himself avenged, had P. remained ignorant . . .”

37 Or, “with any who can no longer feel their anger.” Cope translates: “with all the rest （besides those actually within reach） who are out of sight.”

38 To make the offender feel pain as part of the punishment.

39 Hom. Il. 24.54.

40 φιλεῖν may be translated “to love” or “to like”; φιλία by “love,” “liking,” or “friendship”; for φίλος “friend” alone is suitable. For the two meanings cp. the use of aimer in French, and lieben in German.

41 Aristotle's opinion of husbandry, in which tillage and planting, keeping of bees, fish, and fowl were included, was not nearly so favorable as that of Xenophon in his Oeconomicus. In two lists of the elements of a State given in the Politics, it comes first at the head of the lower occupations. In its favor it is said that it forms the best material of a rural democracy, furnishes good sailors, a healthy body of men, not money-grabbers like merchants and tradesmen, and does not make men unfit to bear arms. On the other hand, it claims so much of a man's time that he is unable to devote proper attention to political duties, and should be excluded from holding office. He further says that husbandmen, if possible, should be slaves （neither of the same race nor hot-tempered, for they will work better and are less likely to revolt）; or, as the next best alternative, barbarians or serfs. The favorable view taken by Aristotle here and in the Oeconomics （probably not his） does not agree with that put forward in the Politics.

42 Spengel reads ἢ ἐν οἷς θαυμάζουσιν αὐτοί and brackets [ ἢ ἐν τοῖς θαυμαζομένοις ὑφ᾽ αὑτῶν]. ἅπασιν, βελτίστοις, and οἷς will then all be neuter.

43 Two of a trade never agree （Hes. WD 25）.

44 Those with whom we are ambitious of entering into competition “in the race for distinction” （Cope）. There is no unfriendliness, whereas envy produces it.

45 A parenthetical remark. Aristotle explains that he is not thinking of merely conventional faults; if, then, one who is ashamed of these is no friend, then one who is not . . .

46 He wishes to see and know the result of the measures taken against those with whom he is angry. Or, it may mean that he wishes the object of his anger to feel his wrath, and to know by whom, and for what, he is punished.

47 By the definitions of anger and hatred.

48 And therefore, having the inclination to be unjust, if he has the power, he will be so.

49 Or simply, “near . . . far from us.”

50 τὰ σωτήρια or some other word instead of τὰ θαρραλέα would be expected, to avoid the tautology. The fact of remoteness inspires confidence, because we do not expect fearful things to happen; while salutary things inspire it if near at hand, because we expect them to happen.

51 It is assumed that the gods will be on our side if we have suffered wrong; suffering wrong rouses anger and at the same time inspires confidence, if our relations with the gods are such that we feel we can rely upon them for assistance.

52 Euripides, Cresphontes: αἰδὼς ἐν ὀφθαλμοῖσι γίγνεται, τέκνον （T.G.F. frag. 457）.

53 Jebb translates, “who have never seen us break down.”

54 The Greek scholiast says: “Euripides, having been sent as ambassador to the Syracusans, to ask for peace and friendship, when they refused said: O Syracusans, if for no other reason than that we are just feeling the need of your friendship, you ought to respect our admiration.” Nothing is known of this embassy. Hyperides has been suggested instead of Euripides.

55 This rendering involves a plural neuter with a plural verb. Others take the actions or things in a good sense, “deeds and fortunes, their own or their ancestors, which they are likely to disgrace.”

56 i.e. when they have done anything disgraceful.

57 When on an embassy to Syracuse, he was asked by Dionysius which was the best kind of brass. On his replying, “that from which the Athenians made their statues of Harmodius and Aristogiton,” Dionysius ordered him to be put to death.

58 χάρις may mean （1） benevolence, the feeling which prompts a favor; （2） an actual favor conferred; （3） gratitude.

59 Probably given to a beggar or vagrant who had nothing to sleep on.

60 That is, should have in view the satisfaction of urgent wants and desires （Cope）.

61 Reading ὅτε; others read οἷς, “by whom.”

62 ἀχαρίστους: the word generally means “ungrateful,” and so Jebb takes it here: “and to make men ungrateful.”

63 The other five categories in Aristotle's list are: relation, position, possession, activity, passivity.

64 Because in that case their motives in rendering the greater service cannot be disinterested.

65 Hdt. 3.14, where the story is told, not of Amasis, by of his son Psammenitus.

66 Jebb renders: “Again men pity when the danger is near themselves,” which may mean when they see something terrible happening to others and likely soon to befall themselves. Vahlen inserts οὐ γὰρ before ἔτι: “for men cease to pity when the terrible comes close to themselves.

67 “When the men, who are in such crises, are good men” （Jebb）. If they were not, their misfortune would appear deserved.

68 The signs and actions, and the demeanor of the sufferer.

69 νεμεσᾶν: “the nobler brother of envy” （Nietzsche）.

70 There is justice both in the punishment of the parricide and in the deserved good fortune of others. The conclusion must refer to the latter; if his like is fortunate, he hopes he may be.

71 Because it is a man's own fault, and pity is only felt for what is undeserved.

72 The first part of the sentence is clear: men are indignant when what good men deserve is possessed by those who are not good. The literal translation o the text as it stands is: “Men are indignant . . . at all the advantages of which good men and those who possess natural advantages are worthy”; but this cannot be right, since there is nothing in natural advantages to arouse moral indignation, there is no question of their being deserved or undeserved. Something may have fallen out like “but they will not be indignant with those who possess natural advantages.” Roemer （Rhein. Mus. 39 p. 504） suggests οὐδ᾽ εἰ τὰ φύσει ἔχουσιν ἀγαθά （understanding νεμεσήσει τούτοις）.

73 δοκεῖν is a stronger word than φαίνεσθαι, indicating an intellectual operation as opposed to an impression received through the senses. The idea is that where anything has been so long in a person's possession, it has come to he regarded as his by right.

74 Hom. Il. 11.542. Only the first verse is given in the received text of Homer; the second is not found in any of the mss. The reference is to Cebriones, a son of Priam slain by Patroclus.

75 It has been suggested to insert μὴ before τυγχάνωσι: “if, although virtuous and worthy, they do not happen to possess such advantages.”

76 Or, “of which others happen to be unworthy.”

77 If some one else possesses the one thing which they think necessary to complete their happiness, they are envious of him, because they consider it ought to be theirs.

78 According to the scholiast, from Aeschylus.

79 Two rocks at the east end of the Straits of Gibraltar, supposed to be the limit westwards of the ancient world.

80 That is, no one will attempt to compete with them in their special branch of study. Roemer reads καὶ πρὸς τοὺς περὶ τὰ τοιαῦτα, translated by Jebb as if there were a full stop at ὑπερέχειν. “In like manner we vie with those engaged in such or such pursuits.”

81 2.4.21.

82 “The same state of mind which is absent in the painful feeling will be present in the joy excited by the opposite occasions,” meaning that, if one set of circumstances produces pain, the opposite will produce pleasure （Cope）. Or, omitting οὐκ before ἔχοντες, “For in the same frame of mind as they are pained （at another's good fortune） they will rejoice in the contrary state of things” （at another's bad fortune）.

83 Something like “although they are within their grasp” is needed to complete the sense.

84 Spending one's money benefits one's neighbor to a certain extent, and beauty is always pleasant to look upon. One does not admire anyone because he is in good health, so much as because he is handsome.

85 “Who have many acquaintances or friends” （Jebb）.

86 λογογράφοι means either the oldest Greek historians （or rather “chroniclers”）, or the writers of speeches for use in the law courts, or of panegyrics.

87 καὶ ἐπὶ τούτοις. According to Cope, an unnecessary parenthetical note （“and on such occasions”）. Jebb refers both τούτων and τούτοις to persons: “tend to show contempt to or about those who.” The “reason” in the translation above is that they suffer from the want of “the highly valued goods.”

88 The πίστις ἠθική is resumed from 2.1.8. As the πάθη and ἕξεις have been discussed already, only the ages and their character remain.

89 One of the Seven Wise Men of Greece.

90 Or, “they do not look at things in a bad light, but in a good,” i.e., they are not always ready to suspect.

91 Social convention is the only law that they know, and they are ashamed if they violate it, because as yet they have no idea of higher laws which may command them to do so.

92 ἦθος “in the widest sense, includes all that is habitual and characteristic; in a limited sense, it expresses the habitual temper or disposition” （Twining）.

93 One of the Seven Wise Men of Greece. The maxim was Μηδὲν ἄγαν, Ne quid nimis, Never go to extremes.

94 Or, “better than they really are.”

95 One of the Seven Wise Men of Greece.

96 Or, “speeches which resemble （or reflect） it” （their character）.

97 i.e., the advantages and distinctions the family possessed of old; such distinctions, when possessed by those of later date, are less thought of.

98 “What makes power worth having” （Cope）.

99 ἐν ἐπιμελείᾳ: “because they are administrators” （Jebb）.

100 The three divisions are noble birth, wealth, and power. The meaning is that the highest kinds of good fortune tend or converge to these （i.e., to noble birth, wealth, and power）. κατὰ τὰ μόρια might also mean “in part.” Hobbes, in his Brief of the Art of Rhetorick, paraphrases: “the manners of men that prosper, are compounded of the manners of the nobility, the rich, and those that are in power, for to some of these all prosperity appertains.”

101 Book 2.12-14, 15-17.

102 Having dealt with ethical and pathetic proofs, Aristotle proceeds to the discussion of topics of enthymemes common to all three kinds of Rhetoric. The difficulty in the Greek lies in the absence of a suitable apodosis to the long sentence beginning ἐπεὶ δὲ ἡ τῶν πιθανῶν. Grammatically, it might be ὥστε διωρισμένον ἂν εἴη, but it by no means follows that “since the employment of persuasive speeches is directed towards a judgement . . . therefore it has been determined how . . . we must make our speeches ethical.” Spengel, regarding ἐπεὶ δὲ . . . βουλεύονται merely as an enlargement of Book 2.1, 2, brackets the passage. Cope suggests that something has fallen out after βουλεύονται: “Since in all the three kinds of Rhetoric the object is to secure a judgement, [I have shown how to put the judges into a certain frame of mind in the discussion of the characters and emotions]. I have also spoken of the characters of the forms of government; so that this part of the subject need no longer detain us.” It is generally agreed that we have not the chapter as originally arranged, although it is not supposed that any part of it is non-Aristotelian （see Cope and note in Jebb's translation）.

103 Both forensic and deliberative.

104 Or, “for in both forensic and deliberative arguments the issue is the state of the case.”

105 Book 1.8.

106 Book 1.3.

107 Book 1.4-8.

108 Book 1.9, 10-15.

109 1.9.40. Amplication is to be understood of the exaggeration of both great and small things. It is most suited to epideictic oratory, in which there is no doubt as to the facts; so that it is only necessary to accentuate their importance or non-importance.

110 As a general rule, from their nature as contraries, although it may not be true in particular cases. If a man is ill, he may also be well, although in particular cases certain qualities may make him more liable to one or the other, e.g. he may suffer from an incurable disease （Schrader）.

111 An argument a fortiori. If a beautiful house can be built, so can a house of any kind; for this is easier.

112 The meaning of the Greek words is quite uncertain.

113 T.G.F. p. 765.

114 Book 1.7.

115 As a starting-point and first principle of knowledge.

116 The Libyan fables were of African origin. They are mentioned by Quintilian （Quint. Inst. Orat. 5.11.20） and belonged to the class of animal fables.

117 The παραβολή as understood by Aristotle is a comparison and application of cases easily supposable and such as occur in real life, for the purpose of illustrating the point in question; the fable, on the other hand, is pure fiction.

118 “Literary knowledge” （Jebb）; “literature” （Cope, Introd. p. 256, who, however, in his annotated ed. explains: “intellectual study and mental exercises in general”）.

119 If we have no enthymemes, we must use examples instead of them; for they are useful for persuasion, although they do not really demonstrate anything. If we have enthymemes, we must use examples in corroboration of them （see 21.3 note）.

120 Putting the comma after σχεδόν.

121 Eur. Med. 294-297.

122 “The idle habits which they contract” （Cope）.

123 Euripides, Stheneboea （frag. 661, T.G.F.）.

124 Eur. Hec. 864-865.

125 Maxims with an epilogue are （1） imperfect enthymemes, or （2） enthymematic in character, but not in form; those without an epilogue are （1） such as are well known, or （2） such as are clear as soon as they are uttered.

126 Something added as a supplementary proof, the why and the wherefore; in Book 3.19 it is used for the peroration of a speech.

127 From Simonides or Epicharmus.

128 Eur. Tro. 1051.

129 See sect. 2.

130 They partake of the nature of, but not of the form of, enthymemes.

131 Author unknown （T.G.F. p. 854）.

132 According to Bentley, from Epicharmus.

133 Meaning that the land would be devastated and the trees cut down.

134 Hom. Il. 12.243.

135 Hom. Il. 18.309.

136 1.15.14.

137 Cf. Thuc. 1.70, where the Corinthians complain of the lack of energy shown by the Spartans, as compared with their own restless and troublesome neighbors, the Athenians.

138 “Want of cultivation and intelligence” （Cope）. “Amour-propre” （St. Hilaire）.

139 In reference to their own particular case.

140 The conclusion must not be reached by means of a long series of arguments, as it were strung together in a chain: cp. 1.2.12, where the hearers are spoken of as unable to take in at a glance a long series of arguments or “to follow a long chain of reasoning” （ οὐδὲ λογίζεσθαι πόρρωθεν）.

141 Eur. Hipp. 989.

142 Or, “by means of the speech it is impossible to prove anything otherwise” （Cope）.

143 Aristot. Top. 1.14. πρῶτον: i.e. “the speaker's chief care should be . . .”

144 The more suitable they will be, and the less they will resemble ordinary, trivial generalities.

145 The demonstrative enthymeme draws its conclusion from facts admitted by the opponent; the refutative draws its conclusion from the same, but the conclusion is one which is disputed by the opponent.

146 Or, “noting in addition” （Victorius）; or, “pointing out, side by side” （Jebb）.

147 Assuming that self-control is good, then if the opposite of good （that is, bad） can be predicated of lack of self-control, this proves the truth of the first proposition; otherwise, it may be refuted.

148 Cf. 1.13.2 note.

149 Authorship unknown.

150 Euripides, Thyestes （Frag. 396, T.G.F.）.

151 The argument is that if there was no disgrace in selling the right of farming the taxes, there could be none in purchasing this right.

152 Pupil of Plato and Isocrates, great friend of Aristotle, the author of fifty tragedies and also of an “Art” of Rhetoric. Alcmaeon murdered his mother Eriphyle. Alphesiboea, his wife, says to him, Was not your mother hated? To this he replied, Yes, but there is a distinction; they said she deserved to die, but not at my hands.

153 Nothing is known of this trial.

154 The argument is that since men beat their fathers less commonly than they do their neighbors, if they beat their fathers they will also beat their neighbors, and the Paris ms. in a longer form of this argument has an explanatory addition to this effect, inserting after ὑπάρχει the words τοὺς γὰρ πατέρας ἧττον τύπτουσιν ἢ τοὺς πλησίον. In a similar passage in Aristot. Top. 2.10 εἰκός （or δοκοῦν） is inserted after μᾶλλον and ἧττον. Welldon suggests that here also the reading should be τὸ ἧττον εἰκός and τὸ μᾶλλον εἰκός （Grote, Aristotle, p. 294）.

155 From the Meleager of Antiphon （T.G.F. p. 885）.

156 In carrying off Helen.

157 The Paris ms. has θανατοῦνται, “are put to death.”

158 Fragment of a speech of Lysias. It was proposed to put up a statue to the famous Athenian general Iphicrates in honor of his defeat of the Spartans （393 B.C.）. This was later opposed by Harmodius, probably a descendant of the tyrannicide. The speech, which is considered spurious, was called ἡ περὶ τῆς εἰκόνος.

159 Or, “the ways of doing this are various” （Jebb）.

160 The illustration is lost or perhaps purposely omitted as well known. The Teucer was a tragedy of Sophocles.

161 It would be absurd to use such an argument against the accusation of a “just man” like Aristides, and to pretend that he is more likely to have committed the crime. It must only be used when the opponent's character is suspect, and lends itself to such a retort.

162 The reference is obviously to Socrates, who claimed that a daimonion （a certain divine principle that acted as his internal monitor） checked his action in many cases. When accused of not believing in the gods, he was able to prove, by his definition of the daimonion, that he was no atheist. Similarly, Iphicrates, by his definition of γενναῖος and συγγενής could refute the allegation that he was ignoble and show that his deeds were more akin to those of Harmodius and Aristogiton than to those of his opponents. Paris could say that he was not intemperate, because he was satisfied with Helen alone. Lastly, Socrates refused an invitation to visit Archelaus, king of Macedonia, because he would be unable to return the benefits received, which would imply his being put to shame, and make the invitation a kind of insult.

163 Of Polycrates.

164 “Just as it is to requite them with evil” （Jebb）.

165 Supplying [λελέκται] περὶ τοῦ ὀρθῶς [χρῆσθαι αὐτοῖς]. Others render “in reference to the use of the word ὀρθῶς” （but ὀρθῶς does not occur in the passage in Aristot. Top. 1.15）. A suggested reading is περὶ τούτου ὀρθῶς εἴρηται.

166 Mantias had one legitimate son Mantitheus and two illegitimate by a certain Plangon. Mantias at first refused to acknowledge the latter as his sons, until the mother declared they were.

167 The name of the mother; or simply, “the woman of Dodona,” like “the woman of Peparethus.”

168 Others read πολίτην, “although he was not their fellow-citizen” （but Chios was one of the claimants to his birthplace）.

169 Something has fallen out, what follows being intended to prove that the best rulers for a state are the philosophers.

170 Epaminondas and Pelopidas. One would rather expect, “as soon as philosophers had the conduct of affairs.”

171 Athenian ambassador to Sparta （371 B.C.）, whose aggressive policy he attacked. His argument is that, if the Eumenides could agree without any loss of dignity to stand their trial before the Areopagus, as described in Aeschylus, surely Mixidemides could do the same. Nothing is known of Mixidemides, but it is clear that he refused to submit his case to it, when charged with some offense.

172 The story is told of Agesipolis （which others read here） in Xen. Hell. 4.7.2. The Argives, when a Lacedaemonian army threatened to invade their territory, were in the habit of alleging that it was festival time, when there should be a holy truce. This obviously left the door open to fraud, so Agesipolis （one of the Spartan kings） consulted the oracle of Zeus at Olympia to ask whether he was to respect such a truce. The reply of the oracle was that he might decline a truce fraudulently demanded. To confirm this, Agesipolis put the same question to Apollo: “Is your opinion as to the truce the same as that of your father （Zeus）?” “Certainly,” answered Apollo. Agesipolis thereupon invaded Argos. The point is that really Apollo had little choice, since it would have been disgraceful for the son to contradict the father.

173 After his defeat at Aegospotami （405 B.C.） the Athenian general Conon, fearing for his life, took refuge with Evagoras, king of Cyprus—a proof, according to Aristotle, of the goodness of the latter.

174 If the genus can be affirmed of any subject, then one or other of the species, which make up the genus, must also be predicable of it. If the proposition to be maintained is, the soul is moved, it is necessary to examine whether any of the different kinds of motion （increase, decrease, decay, change of place, generation, alteration） can be predicated of the soul. If not, the generic predicate is not applicable, and the proposition is refuted.

175 The bad with the good. The exact meaning of βλαίσωσις has not been satisfactorily explained. In the definition given of the retortion of a dilemma, the two opposite things would be speaking truth or untruth; the two opposite consequences, pleasing men and pleasing God.

176 e.g. a man may say that an honorable death should be preferred to a pleasant life, and honest poverty to ill-acquired wealth, whereas really he wishes the opposite. “If then his words are in accordance with his real wishes, he must be confronted with his public statements; if they are in accordance with the latter, he must be confronted with his secret wishes. In either case he must fall into paradox, and contradict either his publicly expressed or secret opinions.” （Aristot. Sophist. Elenchi 2.12, Poste's translation）.

177 This “law” （already mentioned in 23.11） is said to have been an oration on the legal position of mercenaries.

178 Cause and effect.

179 Isoc. 15.173.

180 The peace concluded between the Greeks （although the Lacedaemonians held aloof） and Alexander the Great after the death of Philip of Macedon （336 B.C.）.

181 Lys. 34.11.

182 i.e., after their return, they preferred to leave the city rather than fight. This is Cope's explanation, but the meaning of the clause ὁτὲ μὲν . . . ᾑροῦντο is then somewhat obscure. A more suitable interpretation would be: “At one time they preferred to return from exile at the price of fighting; at another, not to fight at the price of being exiled a second time （St. Hilaire）,” but one does not see how this can be got out of the Greek.

183 The author is unknown.

184 Frag. 2 （T.G.F. p. 792）.

185 Hom. Il. 10.218; cp. T.G.F. p. 801.

186 By pointing out what is likely to deter a man from committing a crime, and vice versa.

187 The argument is: we accept either that which really is, or that which is probable; if then a statement is made which is incredible and improbable, we assume that it would not have been made, unless it was true.

188 Athenian demagogue and opponent of Alcibiades, for whose banishment he was chiefly responsible. When the Four Hundred were set up, he was put to death. Pitthus was an Athenian deme or parish.

189 Understanding διαβεβλῆσθαι. Others read μὴ （for ἢ） δοκοῦσι, “when there seems no reason to suspect them.”

190 The names of traitors were inscribed on a brazen pillar in the Acropolis. Leodamas supported the oligarchic, Thrasybulus the democratic party. In answer to the charge that he had had his name removed from the pillar when his party came into power, Leodamas replied that, if he had been originally posted as an enemy of the people and a hater of democracy, he would have preferred to keep the record, as likely to increase the confidence of the Thirty in him, than to have it erased, even though it branded him as a traitor.

191 If a person has not taken the better course, when he had the chance of doing so, he cannot be guilty.

192 Leucothea was the name of the deified Ino. She was the daughter of Cadmus and the wife of Athamas king of Thebes. The latter went mad and, in order to escape from him, Ino threw herself into the sea with her infant son Melicertes. Both became marine deities.

193 Tragic poet, contemporary of Aristophanes （T.G.F. p. 798）.

194 An early edition, afterwards enlarged. It must have contained something more than the topic of “errors” to be of any use.

195 Sophocles, Tyro, Frag. 597 （T.G.F.）. The reference is to Sidero （ σίδηρος, iron）, the cruel stepmother of Tyro.

196 Thompson's rendering （Introd. to his edition of Plato's Gorgias p. 5）. “Colt” refers to Polus's skittishness and frisking from one subject to another.

197 Eur. Tro. 990.

198 Frag. 4 （T.G.F.）. The name Pentheus is from πένθος （sorrow）.

199 “Admitting the apparent correctness of the opposing argument, we may prove the contradictory of its conclusion by an unassailable argument of our own, which is then called an elenchus” （Thomson, Laws of Thought, section 127）.

200 Isoc. 9.65-69.

201 Or equivocation, in which a single term has a double meaning.

202 Deriving μυστήρια （ μύειν, to close the lips） from μῦς （mouse）.

203 A fragment from the Parthenia （songs sung by maidens to the accompaniment of the flute）. Pan is called “the dog of Cybele,” the great nature-goddess of the Greeks, as being always in attendance on her, being himself a nature-god. The fact that Pindar calls Pan “dog” is taken as a glorification of that animal.

204 κοινὸς Ε῾ρμῆς is an expression meaning “halves!” When anyone had a stroke of luck, such as finding a purse full of money in the street, anyone with him expected to go halves. Hermes was the god of luck, and such a find was called ἑρμαῖον. κοινωνικός is taken to mean （1） liberal to others, or （2） sociable.

205 λόγος: （1） speech; （2） account, esteem.

206 Very obscure and no explanation is satisfactory. The parallel passage in Aristot. Sophist. Elenchi 20.6 is: “Do you being in Sicily now know that there are triremes in the Piraeus?” The ambiguity lies in the position of “now,” whether it is to be taken with “in Sicily” or with “in the Piraeus.” At the moment when a man is in Sicily he cannot know that there are at this time triremes in the Piraeus; but being in Sicily he can certainly know of the ships in the Piraeus, which should be there, but are now in Sicily （Kirchmann）. St. Hilaire suggests that the two clauses are: Do you now, being in Sicily, see the triremes which are in the Piraeus? and, Did you when in Sicily, see the triremes which are now in the Piraeus? The fallacy consists in the two facts （being in the Piraeus and the existence of triremes in Sicily）, true separately, being untrue combined.

207 Thrasybulus deposed the thirty individuals and put down the single tyranny which they composed; he then claimed a thirtyfold reward, as having put down thirty tyrannies.

208 Frag. 5 （T.G.F.）.

209 Hdt. 2.141. The story was that, when Sennacherib invaded Egypt, a host of field-mice devoured all the quivers, bowstrings and leather shield-holders of the Assyrians. Apollo was called Smintheus （ σμίνθος, mouse） and was represented on coins with a mouse in his hand, either as the mouse-slayer and protector of crops, or because the animal was sacred to him. The story, alluded to elsewhere, was of Greek, not of Egyptian origin. Similar panegyrics on ridiculous things or animals included pots, counters, salt, flies, bees, and such subjects as death, sleep, and food.

210 Sophocles, The Gathering of the Greeks （T.G.F. p. 161）, a satyric drama. His not being invited was a mere accident of the disrespect.

211 Assuming a proposition to be convertible, when it is not; it does not follow, assuming that all the high-minded dwell by themselves, that all who dwell by themselves are highminded.

212 The poor want to get money; the rich dance and sing to amuse themselves, or to show that they can do as they like. Exiles can certainly live where they like in a foreign land, but would prefer to live in their own country; the rich, who are not exiles, travel to amuse themselves.

213 The first “is” means “has a real, absolute existence”; the second “is” merely expresses the identity of the terms of the proposition, and is particular; but the sophistical reasoner takes it in the same sense as the first. The same applies to the argument about the unknown.

214 This utterance of Protagoras gave particular offense as apparently implying that the weaker cause was really identical with the worse, so that to support it was to support injustice. But, considering the high moral character ascribed to Protagoras, it seems more probable to take the formula as a statement of the aim of all ancient orators—how to overcome stronger arguments by arguments weaker in themselves.

215 In which the contrary of an opponent's conclusion is proved.

216 i.e., the opponent's enthymeme.

217 Love is regarded as a desire, and therefore as bad as any other desire. It is here included under the general head of want.

218 Incest: Ovid Met. 9.454.

219 The contrary of “good men do good to all their friends” is “bad men do harm to all their friends,” but this is not always true. Jebb gives the objection as: “No, the bad man does not do evil to all his enemies.”

220 Translating ἀεί inserted by Vahlen before ὄντος.

221 That is, if the argument is shown to be not “necessary.”

222 The important point in the conclusion drawn is that the judge thinks it is not his business to decide, because the argument is not necessary, whereas his duty is to decide, not about things that are necessary but about things that are probable.

223 χρόνῳ . . . πράγμασιν. If χρόνῳ be taken to mean the date, there are the following alternatives. The date may be questioned, the facts admitted; both date and facts may be questioned; both date and facts may be admitted, but circumstances may have altered （a pound was worth twenty shillings in 1914, not in 1924）. Others take χρόνῳ to mean the greater number of times the same fact has occurred, πράγμασι the more numerous facts that increase probability. But χρόνῳ can hardly bear this meaning （see Jebb's note）.

224 1.2.18; or, “at the beginning,” i.e., of this book.

225 Aristot. Pr. Anal. 2.27.

226 On the other side, in the opponent's favor.

227 Aristot. Pr. Anal. 2.27.

228 That is, “when the tekmērion is converted into a syllogism.” For tekmērion see 1.2.16.

229 “Intellectual capacity, as evinced in language （or actions）, and seen when the actors argue or make an appeal to the feelings of others, in other words, when they reason or plead with one of the other dramatis personae in the same sort of way as a rhetor might do” （Bywater on Aristot. Poet. 1450a 6, where the text is speaking of the διάνοια of the actors in a play）.