@startwbs GitRepublic_v2.0_WBS

skinparam dpi 300
title GitRepublic Desktop App v 2.0 WBS

* GitRepublic v 2.0

** v 1.1.0 Ngit social
*** issues
**** create issue
**** view issues
**** issue viewer
*** proposal highlights
*** issue and proposal replies

** v 1.2.0 Aedile note functionality 
*** write article
*** write wiki page
*** mailboxes
*** display feed
**** show nostr: addresses
**** add #tags
**** likes
**** quote
**** boost
**** reply

** v 1.3.0 GitRepublic basic
*** About menu
**** profile page
**** notifications
**** settings
*** Edit menu
**** undo/redo
**** cut/copy/paste
**** select all
**** search and replace

@endwbs