@startwbs GitRepublic_v3.0_WBS

skinparam dpi 300
title GitRepublic Desktop App v 3.0 WBS

* GitRepublic v 3.0

** v 2.1.0 Externals
*** zaps
*** wallets
*** REST API
*** elastic search
*** GC-Tradewinds integration
*** GC-Ulysses integration
*** GC-TheFourthEstate integration
*** communities

** v 2.2.0 GitRepublic projects
*** groups
*** feed customization
*** group wiki
*** group knowledge base
*** private repos
*** repo ratings
*** repo badges
*** zap goals for repos and feature branches

** v 2.3.0 GitRepublic project management
*** Kanban issues board
*** definition of project team
**** owners
**** collaborators
**** testers
*** scheduling
*** teleconference

@endwbs