@startmindmap GR Project Structure
title GitRepublic Project Structure

* Project
** Documentation
*** User Manual
*** Wiki Pages
*** Articles
*** Release Notes
** Repos
*** Repo event 1
*** Repo event 2
*** Repo event 3
** Team
*** Admins
**** npub1
*** Collaborators
**** npub2
**** npub3
**** npub4
**** npub5
*** Reviewers
**** npub6
**** npub7
** Planning
*** Epic MVP
**** Feature 1
***** Scenario 1
***** Scenario 2
***** Scenario 3
****** Issue 1
***** Scenario 4
**** Feature 2
***** Scenario 1
***** Scenario 2
**** Feature 3
***** Scenario 1
***** Scenario 2
****** Issue 2
****** Issue 3
***** Scenario 3
*** Epic Video
**** Feature 1
***** Scenario 1
**** Feature 2
***** Scenario 1
***** Scenario 2

@endmindmap