@startgantt GitCitadelRoadmap

skinparam dpi 300
title GitCitadel Roadmap
printscale weekly

' Gantt chart settings
Project starts 2024-09-01
today is 2024-10-19 and is colored in #AAF
footer Today is marked using a gray verticle line

' Project vacations
2024-12-21 to 2025-01-06 is closed

' GitCitadel project tasks
[GitCitadel Jenkins, Gitlab, Wikistr, Njump instance] as [GC1] is colored in MediumPurple
    [GC1] starts 2024-06-01
    [GC1] ends 2024-12-20
    [GC1] is 25% completed
 [GitCitadel ServerMonitoring] as [GC2] is colored in MediumPurple
    [GC2] starts 2024-09-30
    [GC2] ends 2024-10-17
    [GC2] is 100% completed
[GitCitadel Nostrbots] as [GC3] is colored in MediumPurple
    [GC3] starts 2024-10-12
    [GC3] ends 2024-10-26
    [GC3] is 60% completed
[GitCitadel Sybil] as [GC4] is colored in MediumPurple
    [GC4] starts 2024-10-04
    [GC4] ends 2024-10-31
    [GC4] is 10% completed
[GitCitadel Alexandria DevOps] as [GC5] is colored in MediumPurple
    [GC5] starts 2024-09-01
    [GC5] ends 2024-12-03
    [GC5] is 25% completed

' Alexandria product tasks

' v0.1.0
[Alexandria dev] as [A1] is colored in Tan
    [A1] starts at 2024-09-01
    [A1] ends at 2024-11-15
    [A1] is 75% completed
[Alexandria test dev] as [A2] is colored in Tan
    [A2] starts at 2024-10-01
    [A2] ends at 2024-11-15
    [A2] is 15% completed
[Alexandria v 0.1.0 internal] as [A3] happens at [A1]'s end
[Alexandria publishing Douay-Rheims Bible] as [A4] is colored in Tan
    [A4] starts at [A3]'s end
    [A4] ends at 2024-11-17
    [A4] is 90% completed
[Alexandria webapp internal] as [A5] happens at [GC5]'s end
[Alexandria webapp test] as [A6] is colored in Tan
    [A6] starts at [A5]'s end
    [A6] ends 2024-12-20
    [A6] is 10% complete
[Alexandria v 0.1.0 external] happens at [A6]'s end

' v0.2.0
[Alexandria v 0.2.0 kick off] as [A5] happens at 2024-01-11

@endgantt
